### ISSUE TITLE
BUG- INPUT not showing all typed characters

### ISSUE THREAD

**Issue by Forchapeatl** [Avaiga/taipy-gui#1001]
**Description**
Input element not working properly. Some numbers get deleted upon fast typing .I included video for illustration 

**How to reproduce**
A code fragment
```py
import taipy as tp

from taipy.gui import Gui, notify

input_how =''

page="""

<|{input_how}|input|multiline|>
  
"""

Gui(page).run()
```

#Or a sequence of events:

- Just keep typing really fast not all characters will be shown on the input feild. 
- You can also paste some text and try to edit really fast . It won't work as expected

...

**Expected behavior**
All typed characters should be shown on the input feild.

**Screenshots**

https://github.com/Avaiga/taipy-gui/assets/24577149/14d76de2-8052-43cf-8cdd-fa04f765fab7

**Runtime environment**
Please specify relevant indications.
 - OS: [Linux] 22.04
 - Browser: [Chrome] and version
and any other relevant information.

**Comment by FlorianJacta** [comment]
Thank you for your feedback! Could you try the same experiment with a different change_delay? For example,

`<|{input_how}|input|multiline|change_delay=600|>`

Do you have better results? We will be sure to look into your issue.

This behavior ican bedue to the propagation of the visual element value to the bound variable in real-time.
