### ISSUE TITLE
Test ngrok

### ISSUE THREAD

**Issue by florian-vuillemot** [Avaiga/taipy-gui#11]
There is no test on ngrok.

We at least need a test to ensure we can run with or without this package.

This will allow us to validate its optional installation in the CI.

**Comment by dinhlongviolin1** [comment]
I have tried ngrok testing but due to the limitation of having to use their API key to state a ngrok instance, only 1 test instance can be ran at the same time, which is not what we want at the moment since github actions is running multiple instance at the same time. So I have removed it.
