### ISSUE TITLE
Allow early variable binding

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#14]
**Description**

At the current time, variable binding is done when a page is first displayed. Only the variable used in that page would be bound, and therefore accessible from the Gui instance (or to be more precise, from the client data scope).

Let's suppose we have an application with two pages:
  - the app starts by showing page 1.
  - variable 'x' is used on page 2 only.
  - some functions triggered by buttons or controls of page 1 need to update 'x'
    Naturally, we want to refer to 'gui.x' and do our thing.
 Unfortunately, until page 2 is displayed, 'x' does not exist in the Gui object, and the application fails.
 
In the situation of some user code accessing a variable from the Gui object, but fails to find it (it is not bound), no matter if we want to read or write this variable, the Gui object should try to locate the not-yet-bound variable in the global scope (just at it does in the regular magic binding from the page renderers), and bind it if it can.
 
Only when the variable actually cannot be found should the application complain and fail.

Of course, we may want to cache the binding failures if there's a performance hit or, which I think is more relevant, if we don't want to generate the same error message over and over.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
a workaround would be to modify the global variable while the gui variable are not available

**Comment by FabienLelaquais** [comment]
> a workaround would be to modify the global variable while the gui variable are not available

Then you as a developer would need to know whether or not 'page 2', in the example, had been displayed at one point... and use the appropriate variable accordingly. 'x', or 'gui.x'... Hmm does not work for me.

**Comment by FredLL-Avaiga** [comment]
> > a workaround would be to modify the global variable while the gui variable are not available
> 
> Then you as a developer would need to know whether or not 'page 2', in the example, had been displayed at one point... and use the appropriate variable accordingly. 'x', or 'gui.x'... Hmm does not work for me.

I do agree
