### ISSUE TITLE
Initiate the Maps integration

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#153]
See what we can do with Maps from Plotly.

**Comment by FredLL-Avaiga** [comment]
plotly.js
 examples: https://plotly.com/javascript/mapbox-layers/

**Comment by FredLL-Avaiga** [comment]
We could also provide a Gmaps specific control using:
- [a react wrapper](https://www.npmjs.com/package/google-map-react)
- [clusters](https://www.leighhalliday.com/google-maps-clustering)
or more basically
- [from Google Dev](https://developers.google.com/maps/documentation/javascript/react-map)

**Comment by FredLL-Avaiga** [comment]
1st step: support lat/lon as property of chart

**Comment by FredLL-Avaiga** [comment]
```
from taipy.gui import Gui
import pandas as pd

data = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/2015_06_30_precipitation.csv")

marker = { "color": "fuchsia", "size": 4 }

layout = {
			"dragmode": "zoom",
			"mapbox": { "style": "open-street-map", "center": { "lat": 38, "lon": -90 }, "zoom": 3 },
			"margin": { "r": 0, "t": 0, "b": 0, "l": 0 }
		}

md = """
# Test Map
<|{data}|chart|type=scattermapbox|marker={marker}|layout={layout}|lat=Lat|lon=Lon|text=Globvalue|mode=markers|>
"""

Gui(md).run(use_reloader=False)
```
