### ISSUE TITLE
BUG/Enhancement-Manage installation for Taipy on Mac OS

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#168]
**Description**
A Mac user has to install libmagic through Brew by himself to make Taipy work.

**How to reproduce**
- On Mac, create a Conda environment with python 3.8 for example 
- Run:
```
pip install taipy
```

Taipy will not work until the user installs libmagic.

**Expected behavior**
The user should be warned to install libmagic or an exception has to be raised or another solution found. 

**Runtime environment**
 - OS: Mac

**Comment by florian-vuillemot** [comment]
https://app.zenhub.com/workspaces/taipy-613ef328affde6000ff77fb3/issues/avaiga/taipy-gui/211
