### ISSUE TITLE
BUG-Explain page styling

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#180]
**Description**

I don't quite get what page-based styling does or how it work - or should work.

**How to reproduce**

Here is a tiny piece of code:
```
from taipy import Gui
root="""
# Taipy styling
<|page1;page2|navbar|>
"""
page1="""# This is page 1
With some text
"""
page2="""# This is page 2
With more text
"""
gui=Gui(pages={"/":root, "page1":page1})
gui.add_page("page2", page2, "h1 { color:green;}")
gui.run()
```

'page1' has no style.
'page2' has some style.

- When the app first runs, 'page1' is displayed, with no specific style. The '#' header appears in black (or white with a dark theme).
- If page2 is selected, it appears with the '#' headers in green. The style is properly applied.
- If page1 is selected again, the headers remain in green. They should not. Or should they?

Note that the 'root' page is not the issue here. Without it, we have the same behavior:
```
from taipy import Gui

page1="""# This is page 1
With some text
Goto [page2](/page2)
"""
page2="""# This is page 2
With more text
Goto [page1](/page1)
"""
gui=Gui(pages={"page1":page1})
gui.add_page("page2", page2, "h1 { color:green;}")
gui.run()
```

**Expected behavior**

I expected page2 to have green headers, and not in page2.

**Comment by FredLL-Avaiga** [comment]
To make things more consistent, we need to:
- remove the styling from the page when there is none
- handle the block control styles (either by not allowing it or by identifying it if possible)

**Comment by FredLL-Avaiga** [comment]
The new implementation works like this:
- if there is style associated with a page, it is set
- if there is no style associated with the page, the style is cleared
- if the page is embedded in a block control, the style (and head) is ignored
