### ISSUE TITLE
BUG-Markdown style support

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#185]
**Description**

It looks like the Taipy parsing of Markdown does not allow Markdown inline styling.

The Markdown syntax should support the {} syntax as described below.

**How to reproduce**

If a Markdown page uses the following content:
```
# This is page 1 {.blue-class}

With some text in red. {#green-line}
```

And a CSS file would hold:
```
#green-line {
  color: rgb(0, 255, 17);
}

.blue-class {
  color: blue;
}
```

We expect the generated HTML to set the blue-class CSS class to the header, and give the paragraph the id 'green-line'.
The the header would be displayed in blue, and the paragraph, greenish.

**Comment by FredLL-Avaiga** [comment]
for blocks the right markdown syntax is 
```
# This is page 1 {.blue-class}

With some text in red. 
{#green-line}
```
