### ISSUE TITLE
Theme cannot be set for light or dark, except with private APIs

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#195]
**Description**

The theme[dark]/theme[light] configuration parameters are fine, expect they cannot be expressed as a parameter to Gui.run() or as an environment variable.

We must provide an alternative like 'dark_theme' & 'light_theme' that would have the same semantics as 'theme', but for their specific case.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
I propose that we change the name in the config to theme_dark & theme_light instead of theme[dark] ...
Would you agree @FabienLelaquais ?
