### ISSUE TITLE
Add hover text on controls

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#20]
**Description**

Hover information provides tips on what a control does.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by AAstridVH** [comment]
I guess you could use a standard "tooltip" item.

Try, if possible, to respect [these criteria](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html
)

The Material UI React [tooltip with HTML](https://mui.com/components/tooltips/#customization) may work great.

**Comment by FredLL-Avaiga** [comment]
@FabienLelaquais How would you call that property (that would be available on **all** components) ?

**Comment by FabienLelaquais** [comment]
What about hover_text?
I don't fancy _label...

**Comment by FredLL-Avaiga** [comment]
> What about hover_text?
> I don't fancy _label...

hover_text it will be then
