### ISSUE TITLE
BUG- Numpy Import Error (on Jupyter Notebook)

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#208]
**Description**
When importing taipy (on Jupiter Notebook), an error occurs because of a missing import (numpy.typing). The problem is that numpy is not compatible with taipy even if the requirement is said to be satisfied. For example, I had the 1.19 version of Numpy which is not compatible with Taipy but the requirement was satisfied.

I don't know if the problem is only on Jupyter Notebook.

**How to reproduce**
Open a Jupyter Notebook (with a old version of numpy already installed)

`pip install taipy`

`from taipy import Gui`

*Temporary fix**
`pip install numpy==1.21.0`

**Expected behavior**
No error should occur. The correct version of numpy should be installed when installing taipy.

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/98709993/162424845-2a1f37e8-9e4f-452b-ac1e-f7255f358de4.png)

**Runtime environment**
Jupyter Notebook

**Comment by jrobinAV** [comment]
I believe the problem appears as well if instead of running `pip install taipy` we run either of the following: 
-  `pip install taipy-rest`
-  `pip install taipy-gui`
-  `pip install taipy-core`

Can you check that?

If so, we will move the ticket from taipy-gui to taipy repo.

**Comment by FlorianJacta** [comment]
I have some difficulty installing/uninstalling in Jupyter Notebook for whatever reason (the uninstallation is always running, it is not related to taipy). I will try again on Monday

**Comment by florian-vuillemot** [comment]
`typing.NDArray` comes with NumPy 1.21 (https://numpy.org/devdocs/reference/typing.html).
It's typing for Numpy; we don't need it.

@FlorianJacta can you please try again ?

PR is here: https://github.com/Avaiga/taipy-core/pull/145

**Comment by FlorianJacta** [comment]
The importation seems to work.

**Comment by florian-vuillemot** [comment]
https://github.com/Avaiga/taipy/issues/33

**Comment by florian-vuillemot** [comment]
Fix in: https://github.com/Avaiga/taipy-core/releases/tag/1.0.1
