### ISSUE TITLE
Add all sorts of chart examples to user manual

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#21]
**Description**

Taipy aims at simplifying the access to advanced graphics such as charts.
However, the access to the expressivity of Plotly is constrained by the understanding of this large library.

Because we don't want to have developers engaged in learning all of Plotly in order to achieve their goals, on potential way is to provide multiple examples, as simple and different as possible, to users can basically copy and paste provided code snippets (control expressions) to achieve most of their goals.

**Acceptance Criteria**
- [ ] The User Manual section for charts has a significant number of different example to start with.

**Comment by FredLL-Avaiga** [comment]
@FabienLelaquais Could you add a list of the charts that you'd like to see in these demos ?

**Comment by FredLL-Avaiga** [comment]
@FabienLelaquais Where should I put the samples ? 
Is there a dedicated directory or repository (close to the doc) ?

**Comment by FredLL-Avaiga** [comment]
pushed 3 examples  to front-end-experiments/doc
- demo-chart-1
- demo-chart-2
- demo-chart-3
