### ISSUE TITLE
Page scopes

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#231]
**Description**

In the situation where the application is large, one may want to create the user interface where pages are located in different source files. However, the variables that these pages reference will always be searched in the global application scope (where the Gui instance is defined).

The goal of this issue is to allow the creation of pages in a given module file, using variables located in this module.
Pages themselves will have to be added to the Gui instance at a global level, but the variable name aliasing problem will disappear.

The global scope (the scope of the main module) will remain the fallback scope.

**Proposal**

In a module, one could create a page:
```
some_variable = <some_value>
page = Markdown("<|some_variable|>")
```

Then the `page` variable would be imported by the main module where it can be added to the Gui.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by dinhlongviolin1** [comment]
Task estimation is only for reference
