### ISSUE TITLE
Authorization applied to pages

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#232]
**What would that feature address**

With the authentication & authorization features, Taipy is able to identify a user as being granted a number of roles.
We want to leverage this feature so that the graphical user interface serves pages that potentially depend on the connected user roles.

Developers should be able to precisely indicate what user roles can access what page content: starting with a common, public page, users can authenticate, and the back-end associates roles for that user. From now on, these roles are used to control which pages the
user can access.

***Description of the ideal solution***

I don't see the necessity of dealing with user roles at the visual elements level: that would greatly complicate the definition of pages, and one can tune the access to elements on different pages, as long as Taipy has a way to define different page content based on different roles.

As a programmer, there should be a way to register different page contents depending on the assigned user roles. 

Something like:
```
page = RestrictedPage(
    { PublicRole, Page(...) },
    { Role1, Page(...) },
    { [Role2, Role3], Page(...) }
)
gui.add_page(page)
```

***Caveats***

- The definition of what a role is is still unclear, making proposals for APIs impossible.
- It's also unclear if we want to prevent users to access pages, or allow users to access pages that other users cannot.
  (meaning: do roles add or remove access rights).
- In the example above, what if a user has Role1 and Role2?

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by jrobinAV** [comment]
The roles are defined in the specification document [here](https://docs.google.com/document/d/1Yrinpxd1Ihco6dTl4nPMW_3sAgVlohE2pcluUDbG8vU/edit). This should help answer the first and second caveat.
In the implementation section, the role hierarchy could help to answer the third caveat.
