### ISSUE TITLE
Control like an input for password

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#238]
**What would that feature address**
Now it is not possible to have an input for password so without auto complete and without seeing the password. 

***Description of the ideal solution***
The goal will be to have a similar control as the input control with type="password" that will allow the user to write its password without seeing the actual input

***Caveats***
It is a new control.

***Other options***
Adding type="password" in input control.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
As a first step I'll add a property password to the field control.
In the future, we might to find a way to encode the input data ...
