### ISSUE TITLE
No parent nodes in multiple selections of trees

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#241]
**Description**
Now when someone wants to select multiple scenarios, he must hold ctrl. If he wants to expand a new branch to select a child node in a branch, he must select a parent node. He then has in his selection, parent nodes that are not useful and hard to handle.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
2 fold-answer to this:
- allow to expand nodes without selecting it
- allow children only selection

What do you think @FlorianJacta ?

**Comment by FlorianJacta** [comment]
For the second option, it must be a parameter if we choose this one. I  think it has a lot of value for trees. It is rare to want to select a parent node and if the user wants to do something with the parent node. He can take it from the id if the id of the node is the path (/grandparent_node/parent_node/leaf_node)

I think the first option should be the normal behaviour when we click just on the arrow it should always expand and not select. We could make it bigger to make it easy.

**Comment by FredLL-Avaiga** [comment]
We're on the same line :-)
property is select_leafs_only (False by default)
