### ISSUE TITLE
Undo/Redo functionality in the user interface

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#26]
### Description

Edition in the front-end should be undoable (and redoable).

### Issues to be adresses

- Whether the back-end should trigger new pipeline executions or not is a decision made by the programmer.
- Whether the data sources are updated is a decision made by the programmer.
- Undo/redo in paginated tables should bring the modified row in the visible area.
- Multi-user must be addressed.

**Comment by jrobinAV** [comment]
This seems:
- Too far from the current spirit of Taipy
- Obsolete. Especially regarding the new core visual elements
- unrealistic 
@FabienLelaquais Should we close the ticket?
