### ISSUE TITLE
BUG-Table control -- on_add not recognized unless on_delete present

### ISSUE THREAD

**Issue by mshell99** [Avaiga/taipy-gui#266]
**Description**
Table created by a table control with on_add, but not on_delete will not have add capabilties

**How to reproduce**
A code fragment
```
from taipy import *;
...
md="<|{data}|table|on_add=on_add_fn|>
```

Or a sequence of events:
- Click this button
- Set that control to that value
...

**Expected behavior**
Description of what would be the expected outcome.

**Screenshots**
When available and relevant, screenshots better help show the problem.

**Runtime environment**
Please specify relevant indications.
 - OS: [e.g. Linux, Windows] and version
 - Browser: [e.g. Chrome, Edge, Safari] and version
and any other relevant information.

**Comment by jrobinAV** [comment]
DUPLICATE
