### ISSUE TITLE
Allow filtering on table columns

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#27]
**What would that feature address**

We want to allow users to select a filter from a table header to focus on a subset of the data.
The filter itself will pick one or several existing value and discard the rows that don't match.

***Description of the ideal solution***

Excel-like filtering.

***Caveats***

Some complex filters, like on numerical fields, might have to be implemented on the server.
Then the problem is how to select those filters from the front-end.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create a demo that shows the feature
- [ ] Ensure documentaion is updated

**Comment by FredLL-Avaiga** [comment]
Not sure client filtering would bring any value.
I think we should implement a back-end filter (inthe same way as the sort is done)
For the UI I propose to show a filter icon if filtering is available (property filter[col nome]=True or filter=True)
The icon would be different if a filter is set 
a small popover would open on click and allow the filter to be entered
filter should be different depending on the type of the column 
- text => filter by start if simple text and support for wildcards
- numeric or date => less than,  greater than 
- support for not and or

Another possibility would be to have a global popover for managing filter for the whole table with the possibility to add different filters on different columns combined with and/or ...

Any thought @FabienLelaquais ?

**Comment by FabienLelaquais** [comment]
In my opinion, Client filtering does bring value. For broad data discovery.
Now I like your approach, which addresses this use case.
The 'or' or 'not' operator seem a bit overkill though.

And I also think that back-end filtering would be... code. Resulting on another DataFrame. I suspect we can live a long time without it for the time being.

**Comment by FredLL-Avaiga** [comment]
> In my opinion, Client filtering does bring value. For broad data discovery.
> Now I like your approach, which addresses this use case.
> The 'or' or 'not' operator seem a bit overkill though.
> 
> And I also think that back-end filtering would be... code. Resulting on another DataFrame. I suspect we can live a long time without it for the time being.
> 

Front end filtering is complicated with pagination...
