### ISSUE TITLE
Add a width property to indicator control

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#276]
**Description**
It will allow to change the width of the indicator easily like other controls.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
Also added a height property for vertical orientation
