### ISSUE TITLE
BUG- Cannot change the State of a variable twice in the same block

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#286]
**Description**
In Taipy-Gui 1.1.0, it is not possible to change the state of a variable twice or more. The new value would not be assigned. On the code below, the first `state.ffilter` will be well assigned but not the second.

**How to reproduce**
```python
from taipy.gui import Gui, State
import pandas as pd
import typing as t

sm_dayofweek = [('0','Mon'),('1','Tue'),('2','Wed'),('3','Thu'),('4','Fri'),('5','Sat'),('6','Sun')]
sm_day_selected = None

data = pd.DataFrame({"Col 1": [1, 2, 3], "Col 2": [10, 20, 30], "Col 3": [100, 200, 300]})
ffilter = [True, True, True]

def change_days(state: State, var, val):
    print(f"change_days(state: State, var: {var}, val: {val})")
    state.ffilter = pd.Series([True, True, True])
    new_filter:t.List[bool] = [False, False, False]
    for i, v in enumerate(state.ffilter):
        new_filter[i] = str(i) in val
    state.ffilter = pd.Series(new_filter)
    print(pd.Series(new_filter))
    print(state.ffilter)

md = """
<|{sm_day_selected}|selector|lov={sm_dayofweek}|on_change=change_days|dropdown|multiple|value_by_id|>
<|{data[ffilter]}|chart|>
"""

Gui(md).run(use_reloader=False)
```

**Expected behavior**
We should be able to change the state of a variable twice or more.

**Runtime environment**
Please specify relevant indications.
 - OS:Windows
 - Taipy-Gui 1.1.0

**Comment by FredLL-Avaiga** [comment]
issue is linked to the protection to not enter in an infinite loop on update
`gui.py:344`

I suppose `self.__modified_vars_update_var` is not thread safe
