### ISSUE TITLE
Add a multi line property for the input visual element

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#333]
**Description**
The goal would be to be able to write texts on multiple lines in the 'input' visual element. It can have multiple uses. Maybe, a new 'multiline' property has to be created for this purpose.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
3 new properties for input:
- multiline: boolean
- rows: optional integer
- cols: optional integer
@FabienLelaquais What do you think of the property names ?

**Comment by FabienLelaquais** [comment]
I discussed, I really don't like those `rows`/`columns` names, although indeed these properties are the ones used in the `textarea` HTML tag.
What about `show_length` and `show_lines`? (`text` does not really work...)

**Comment by FredLL-Avaiga** [comment]
width_in_rows / height_in_cols ?
Or width/height with some docs
https://mui.com/material-ui/api/text-field/
no cols in here but we have rows / minrows and maxrows

I really think we should expose multiline and rows (maybe use it as minRows) and be consistent with MUI and HTML @FabienLelaquais

**Comment by FabienLelaquais** [comment]
My issue really is the language.
Line (for multiline), Row (for, well rows).

Our target is not HTML or MUI developers. Rather the contrary.
Rows is (for good reasons) heavily used in the context of tables...
And I can see nothing better than *multiline*.

**Comment by FredLL-Avaiga** [comment]
line ? boolean ? meaning multi ?
row : optional integer ?

**Comment by FabienLelaquais** [comment]
What I'm saying is that the same semantic object ("series of characters with no carriage return") is represented with two words.
- "Line" in "multiline"
- "Row" in "rows"

That's what I don't like.

I do understand the HTML+MUI argument. Just that I don't buy it.
I would certainly use 'line' everywhere.
-> "n_lines", "line_number", "lines_shown" (show_lines really sounds like a Boolean  property).

"Length" is usually what we would like for the x dimension. Makes no sense here.
"line_length", may be ?

**Comment by FredLL-Avaiga** [comment]
I think the complexity here is that we want to define the "size" of the element and not limit the content ...
I think multiline is quite understandable
I suppose lines_shown is the most evident ...

**Comment by FabienLelaquais** [comment]
Yeah yeah, I get that.

multiline is a no-brainer.
lines_shown is, well, the best I could come up with.
Now length_shown might then work as well horizontally, don't you think?

By the way, I don't get that 'columns' idea anyway:
How do you properly display 'wwwww' and 'iiiii' with a non fixed-size font?

**Comment by FredLL-Avaiga** [comment]
Cols I suppose they use em for width...
I don't like length_shown as it might be confused to the number of characters...
