### ISSUE TITLE
Catch errors when wrongly updating a TaipyNumber

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#337]
**Description**
An error is raised when a TaipyNumber is wrongly updated but the traceback doesn't contain useful information to let the user know about the issue.

**How to reproduce**
Update a TaipyNumber by the wrong type (list).

**Expected behavior**
We should get a better Traceback in order to let the user find the error.

**Comment by FredLL-Avaiga** [comment]
Catching a broader exception allows to give a better feedback to the user
Traceback is not necessary here (except for us ;-) )
