### ISSUE TITLE
Give control over navigation

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#345]
**Description**

Users may want to control how navigation is handled: under certain circumstances, navigating to some page could actually be tampered in a way the end-user is redirected to another.

A typical use case would be the "Bottom Line" page: you want to provide the end-user all the results of all the processes that were triggered so far. You as a developer may want not to display information if it is not available.
Partials help doing this, but the layout may have to be seriously affected. You would then want to create different pages reflecting different outcomes, and, when this "Bottom Line" page is requested, select the one that best fits the current status of the application.

**Proposed solution**

Add a `on_navigation(State, page_name): str` callback function to the `Gui` instance.

When the application switches to some page (in *page_name*), the callback is invoked. From the variables stored in `State`, the programmer may want to redirect to another page, whose name would be the returned value.

Should the page name be changed, `on_navigation()` would have to be called again.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
@FabienLelaquais 
Why "Should the page name be changed, on_navigation() would have to be called again." ?
