### ISSUE TITLE
deprecation warning json encoder

### ISSUE THREAD

**Issue by FredLL-Avaiga** [Avaiga/taipy-gui#349]
**Description**
flask/json/provider.py:188: DeprecationWarning: Setting 'json_encoder' on the app or a blueprint is deprecated and will be removed in Flask 2.3. Customize 'app.json' instead.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
@dinhlongviolin1 I think you've handled this one by upgrading flask to 2.2 ?

**Comment by dinhlongviolin1** [comment]
Yes I did
