### ISSUE TITLE
BUG- Table Control -- Boolean data not shown when table is editable

### ISSUE THREAD

**Issue by mshell99** [Avaiga/taipy-gui#365]
**Description**
If a table control has a boolean column and the table is editable. The boolean "switch" indicator is not shown, only the edit pencil icon
**How to reproduce**
df is a DataFrame with a boolean column
md = """
<|{df}|table|on_edit=on_table_edit|>
"""

**Comment by Dr-Irv** [comment]
I installed the current version of `taipy-gui` as of commit 45795dade1085dcb777fcdceee46ed72b81f0f44 which should include #367 .   Consider the following example:
```python
import pandas as pd
from taipy import Gui
from taipy.gui import State

df = pd.DataFrame({"x": [1, 2, 3], "flag": [True, False, True]})


def myedit(state: State, varname: str, action: str, payload: dict):
    temp_df = state.df.copy()
    temp_df.loc[payload["index"], payload["col"]] = payload["value"]
    state.df = temp_df


def printit(state: State):
    print(state.df)


page = """
<|{df}|table|height=max-content|width=max-content|show_all=True|on_edit=myedit|>

<|print|button|on_action=printit|>
"""


if __name__ == "__main__":
    Gui(page=page, css_file="first").run(async_mode="threading", dark_mode=False)
```
The table is editable, but for the boolean property, I can't use the switch to do the actual editing of the value.  If I do click on the pencil, I can change the value by typing it in, and the value is updated in the dataframe as illustrated by clicking on the "Print" button.  But the switch value is not updated  in the browser when the table value is updated.

@FredLL-Avaiga Can you look into this?

**Comment by FredLL-Avaiga** [comment]
I suppose because the value typed and sent is a string.
A quick workaround would be to transform it to a boolean in your on_edit.
I'm not sure if we really want to cast the values before passing them to on_edit or simply pass everything as a string to allow more freedom ...

**Comment by FredLL-Avaiga** [comment]
I suppose the right thing to do is provide both value (casted and original string)
I'm on it (and for numbers also)

**Comment by FredLL-Avaiga** [comment]
The value is now casted to the type of the column and I've added a user_value: str (the value as entered by the user) to the payload
