### ISSUE TITLE
BUG- var_name in on_edit() for tables doesn't provide name of DataFrame

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-gui#368]
**Description**
If you have an editor for a table, then the value of `var_name` passed into the `on_edit()` function doesn't identify the name of the DataFrame.

**How to reproduce**
A code fragment
```python
from taipy import Gui;
from taipy.gui.state import State
import pandas as pd
df = pd.DataFrame({"x":[1,2,3]})

def myedit(state: State, var_name: str, action: str, payload: dict):
    print(var_name)

page = "<|{df}|table|id=df|on_edit=myedit|>"

if __name__ == "__main__":
    Gui(page=page).run()
```

Then just edit an element and click the checkbox, and it will print `_TpD_tpec_TpExPr_df_TPMDL_2` .  

**Expected behavior**
I expected it would print `df`

**Screenshots**
N/A

**Runtime environment**
Please specify relevant indications.
 - OS: Windows 10
 - Browser: Chrome  104.0.5112.81

**Comment by FredLL-Avaiga** [comment]
Hi @Dr-Irv, 
No need to add a tag property, you should get the right variable name in your on_edit function when the linked PR is merged

**Comment by Dr-Irv** [comment]
> Hi @Dr-Irv, No need to add a tag property, you should get the right variable name in your on_edit function when the linked PR is merged

Great!

**Comment by Dr-Irv** [comment]
I was able to pull your PR and install it and it worked.  Thanks.
