### ISSUE TITLE
Allow ability to get and set state objects via strings

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-gui#369]
**Description**
API improvement.

I'd like to use the same `on_edit()` function on different tables.  But the way to access the associated pandas `DataFrame` requires you to know the name of the variable used to create the table, because the variable name becomes an attribute of the passed in `State` object.

I'd like to propose that you add `set` and `get` methods to the API for `State`.  

So instead of having to write  `table = state.df.copy()`, I could write `table = state.get("xxx").copy()`, and instead of having to write `state.xxx = table`, I could write `state.set("xxx", table)`.

**Comment by FredLL-Avaiga** [comment]
Hi @Dr-Irv 
You can already use 
- getattr(state, "xxx") 
- setattr(state, "xxx", value)

**Comment by Dr-Irv** [comment]
> You can already use
> 
> * getattr(state, "xxx")
> * setattr(state, "xxx", value)

Thanks.  That worked.
