### ISSUE TITLE
BUG- For tables, the `DataFrame` objects can't be a member of a class

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-gui#370]
**Description**
We store `DataFrame` objects in python dataclasses.  When you do that, updates to the tables are not displayed.

**How to reproduce**

```python
import dataclasses as dc

from taipy import Gui
from taipy.gui.state import State
import pandas as pd


@dc.dataclass
class MyData:
    resources: pd.DataFrame


mydata = MyData(pd.DataFrame({"x": [1, 2, 3]}))


def myedit(state: State, var_name: str, action: str, payload: dict):
    temp_df = state.mydata.resources.copy()
    temp_df.loc[payload["index"], payload["col"]] = payload["value"]
    state.mydata.resources = temp_df


def myedit2(state: State, var_name: str, action: str, payload: dict):
    temp_df = state.resources.copy()
    temp_df.loc[payload["index"], payload["col"]] = payload["value"]
    state.resources = temp_df


resources = mydata.resources

page = """
## Using mydata.resources does not update

<|{mydata.resources}|table|width=max-content|id=mydata.resources|on_edit=myedit|>

## Using resources does update

<|{resources}|table|width=max-content|id=resources|on_edit=myedit2|>
"""

if __name__ == "__main__":
    Gui(page=page).run()


```

A sequence of events:
- If you edit the first table, the new values don't show up
- If you edit the second table, the new values do show up

**Expected behavior**
You should be able to use members of classes as `DataFrame` objects in the table description.  If you have lots of tables, having a local variable for each table really isn't great programming practice.  This has to do with how you do the bindings and that tables have to come from an expression in an f-string.

**Runtime environment**
Please specify relevant indications.
 - OS: Windows 10
 - Browser: Chrome

**Comment by Dr-Irv** [comment]
I'm going to attempt to fix #368 #369 #370 by adding a `tag` descriptor to the markdown that represents the string to use to pass into the `on_edit` methods as the varname, and adding the `get` and `set` messages to `State`

**Comment by FredLL-Avaiga** [comment]
Hi @Dr-Irv 
You can work with class instances in state as you work with dict :
when you modify an instance, you need to re-affect it to the state so that Taipy can detect the change

ie this should work:
```
temp_df = state.mydata.resources.copy()
temp_df.loc[payload["index"], payload["col"]] = payload["value"]
state.mydata.resources = temp_df
state.mydata = state.mydata
```

**Comment by Dr-Irv** [comment]
Thanks.  That worked.

**Comment by Dr-Irv** [comment]
> Thanks. That worked.

Although that last line is quite counter-intuitive!
