### ISSUE TITLE
DOCS - Contributing documentation isn't clear

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-gui#372]
**Description**
It isn't clear whether you can do development on `taipy-gui` without installing all of the other parts of `taipy`, and if that's the case, what is the procedure to do so.

I followed the instructions in `CONTRIBUTING.md`, cloned this repo, and wanted to start working with it.  The contribution instructions say to do the command `pipenv install --dev` and I did that.

I followed that with `pipenv shell` and `pip list`, and it shows that `taipy-config` is installed, but `taipy` is not.  So if I try to run a simple program that has `from taipy import Gui`, then it doesn't find the `Gui`, because this project `taipy-gui` is not installed and in the corresponding `site-packages` folder, there is `taipy`, but not `taipy/gui`.

So can you clarify how to set up a dev environment for a single project, or whether you need to install all of them, and, then, if so, in what order, and, finally, how do you install things so that the when you are debugging, it is using the version of the code in the cloned project, as opposed to something that is installed?

This certainly applies to all packages...

**Comment by Dr-Irv** [comment]
Also, let's say I change something in the typescript.  It isn't clear how to recompile the typescript to javascript to test the new code.  `setup.py` has a `build_py` step that only works if the file `src/taipy/gui/webapp/index.html` doesn't exist.  I tried this sequence:
```text
cd gui/dom
npm ci
cd gui 
npm ci --omit=optional 
npm run build
pip install .
```
Also, it isn't clear what to do to install the right versions of `npm` and `node`

So instructions on how to work with the typescript code and debug it would be very helpful.

**Comment by FredLL-Avaiga** [comment]
you should be able to 
cd gui
npm run build (or npm run build:dev to get source maps)

**Comment by Dr-Irv** [comment]
> you should be able to cd gui npm run build (or npm run build:dev to get source maps)

But then how does running a test program know to use the GUI code in the local git repo vs. what is installed in the environment?
