### ISSUE TITLE
DOC - Controls extension package documention

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#383]
**Description**

the control set extension API needs to be documented: Python and Javascript sides.

**Acceptance Criteria**
- [ ] The two packages are documented

**Comment by FredLL-Avaiga** [comment]
need to choose a doc format for ts ...
Do you have any recommendation @FabienLelaquais ?

**Comment by FabienLelaquais** [comment]
Funny you asked.
That's exactly what I was wondering....

What I would do is document things in the types.ts (or whatever file you've chosen in the "types" property in your tsconfig.json), using JsDoc.
I'll make sure that gets properly integrated in the manual, like I did for REST.
The point is that you want to generate that doc locally in taipy-gui, and redo the thing in taipy-doc...

**Comment by FredLL-Avaiga** [comment]
I'll start documenting the code and check that the doc is brought over to the d.ts file as the distributed taipy-gui.d.ts is an extract of the generated tai-gui.gen.d.ts ...

What do you mean "redo the thing in taipy-doc" ?

**Comment by FredLL-Avaiga** [comment]
using the documented taipy-gui.d;ts file in an extension project:
![image.png](https://images.zenhubusercontent.com/613efb225a9c163a3da6610f/79357764-60eb-445c-ac1f-0670fbbaf9f0)

**Comment by FredLL-Avaiga** [comment]
I suppose it would be nice to have a link to the taipy extension doc ...

**Comment by FredLL-Avaiga** [comment]
now using [TypeDoc ](https://typedoc.org/guides/overview/) 
with possibly [typedoc-plugin-markdown](https://www.npmjs.com/package/typedoc-plugin-markdown) for md generation
or a json output that might be easier to handle ?

**Comment by FabienLelaquais** [comment]
> What do you mean "redo the thing in taipy-doc" ?

What I meant was: once we can generate the doc locally, and especially rely on the ide intellisense, this doc will have to be integrated in the global doc set, in taipy-doc. Redo is not a proper wording of what I mean.

**Comment by FabienLelaquais** [comment]
> now using [TypeDoc ](https://typedoc.org/guides/overview/)

That really looks excellent.

> with possibly [typedoc-plugin-markdown](https://www.npmjs.com/package/typedoc-plugin-markdown)
> for md generation

That will certainly be the proper route, but we'll have to give it a try. I haven't seen it yet.

> or a json output that might be easier to handle ?

Probably not, but who knows...

**Comment by FabienLelaquais** [comment]
> I suppose it would be nice to have a link to the taipy extension doc ...

I'm... not sure I get this one.

**Comment by FredLL-Avaiga** [comment]
I mean to put a link to the global extension doc and to the python doc in the tsdoc ...

**Comment by FabienLelaquais** [comment]
I see. Yes indeed.
When we integrate.
