### ISSUE TITLE
Use the latest Taipy logo as favicon

### ISSUE THREAD

**Issue by FredLL-Avaiga** [Avaiga/taipy-gui#385]
**Description**
Use the latest Taipy logo as favicon

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
@AAstridVH Could you attach them here ?
As ico and png files :-)

**Comment by FredLL-Avaiga** [comment]
It seems that @FabienLelaquais has the resources

**Comment by FabienLelaquais** [comment]
Indeed.
https://drive.google.com/file/d/1QHloS6hXK1t_uRyJ3LVF1M3Z7pCx8aiR/view?usp=sharing

**Comment by FredLL-Avaiga** [comment]
The current favicon.png is 192x192 ...
Do you have an ico version (64x64) ?

**Comment by AAstridVH** [comment]
Sure I will send you this!

**Comment by AAstridVH** [comment]
Here we are

![Icon 64](https://user-images.githubusercontent.com/96520448/187387648-79075b1a-a333-4f77-9865-4d121d423106.png)
![Icon 64](https://user-images.githubusercontent.com/96520448/187387654-407ca06e-0219-4044-b9ee-77a193d4486f.svg)

And the .ico

https://drive.google.com/drive/u/0/folders/1tSZ0RPn66kpMV8Ky6rDtq0UZunO8fGWL

**Comment by FredLL-Avaiga** [comment]
The resources we currently have are :
- favicon.ico (64x64) file
- favicon.png (192x192) file

@AAstridVH Do you have these in these resolutions  or do you think we should use the files you provided?

**Comment by AAstridVH** [comment]
If I remember well, these icons have a glow effect, which is not consistent in every situation depending, in particular, on the background color. Could you provide me a screenshot of the display area?
We'd better use the icons I provided if it is very dark or light and offer a strong enough contrast.

**Comment by FredLL-Avaiga** [comment]
They're not use on the display area but as page favicon
```
    <link rel="manifest" href="/manifest.json" />
    <link rel="icon" type="image/png" href="{{favicon}}" />
    <link rel="apple-touch-icon" href="/favicon.png" />

```
and in manifest.json
```
  "icons": [
    {
      "src": "favicon.png",
      "type": "image/png",
      "sizes": "192x192"
    },
    {
      "src": "favicon.ico",
      "sizes": "64x64 32x32 24x24 16x16",
      "type": "image/x-icon"
    }
  ],

```

**Comment by AAstridVH** [comment]
Oh, OK, I understood it was some kind of loading or welcome screen, which make no sense regarding the issue title haha, my bad!
So yes, it's better to use the same icons everywhere!

**Comment by FredLL-Avaiga** [comment]
Can you attach the right files here @AAstridVH ?

**Comment by AAstridVH** [comment]
Sure.

The 192px PNG icon.
![favicon](https://user-images.githubusercontent.com/96520448/187464659-90001dd1-4828-4ed2-bf2e-346e8ffbae62.png)

The .ico cannot be directly attached to GitHub because its format is not accepted.

https://drive.google.com/file/d/1pnHeIZQtSrYTq-apa70dIq-OPZzI_xd1/view?usp=sharing

**Comment by FredLL-Avaiga** [comment]
Thanks @AAstridVH 
The GDrive shares an svg file is it the same as an ico file ?

**Comment by AAstridVH** [comment]
My bad, this one is the converted version https://drive.google.com/file/d/18jMHYYg47Jrz-_Ws8Eh5SsGCJkYZ0nsD/view?usp=sharing

**Comment by FredLL-Avaiga** [comment]
Tx @AAstridVH but I believe this ico file is 32x32 instead of 64 ?

**Comment by AAstridVH** [comment]
Indeed 😫, but I have no idea why. Seems like the SVG to ICO conversion divides the size by two. I'm gonna export it in SVG 128, hoping this will do the trick. I keep you updated.

**Comment by AAstridVH** [comment]
Ok the website I used always make .io 32px*32px for some reason. After trying 4 different websites, this result seems to be satisfying https://drive.google.com/file/d/1SbnluVfpWsma7k-IJLyUSjpbP08VJwkn/view?usp=sharing

**Comment by FredLL-Avaiga** [comment]
👌
Tx

**Comment by FredLL-Avaiga** [comment]
As @FabienLelaquais noticed there's quite a margin on the logo.
@AAstridVH Can you priovide the same files with less/no margin ?

**Comment by AAstridVH** [comment]
Reduced it a bit, but must keep the margin because of the spreading of the glow effect. How about this one?
We could also drop the glow effect if @FabienLelaquais agrees.

https://drive.google.com/drive/u/0/folders/1tSZ0RPn66kpMV8Ky6rDtq0UZunO8fGWL

**Comment by FredLL-Avaiga** [comment]
Not sure the glow effect is visible ...
![image.png](https://images.zenhubusercontent.com/613efb225a9c163a3da6610f/fa4a4064-8b60-4565-99d5-75f69eb0ca35)

**Comment by AAstridVH** [comment]
Yeah, the result is a bit blurry. I don't really like it, tbh.

Here's the icon without the glow effect. :)

https://drive.google.com/file/d/1LTJENjF_7_96eZU3pQ3cVLJq8v5o0fA-/view?usp=sharing
