### ISSUE TITLE
BUG- file_selector not setting the filename

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-gui#423]
**Description**
When using a file selector, the filename variable is not getting set.  The file is uploaded to the server, but the global variable doesn't reflect the filename.

**How to reproduce**

```python
from taipy import Gui
from taipy.gui import State

filename = "UNKNOWN"


def print_filename(state: State):
    print("filename is ", filename)


page = "<|{filename}|file_selector|on_action=print_filename|>"

if __name__ == "__main__":
    Gui(page=page).run()


```

Sequence of events:
- Click the file selector button and pick any file
- You will get a message that says the file has been uploaded
- The variable `filename` is still `UNKNOWN`
...

**Expected behavior**
The variable `filename` should be a string pointing to the name of the file.

**Runtime environment**
Please specify relevant indications.
 - OS: Windows 10
 - Browser:  Chrome 105.0.5195.102 
 - python 3.10.4

**Comment by FredLL-Avaiga** [comment]
Hi @Dr-Irv,
When I test your example adding a field to show the filename it is updated.
```
page = """<|{filename}|file_selector|on_action=print_filename|>

<|{filename}|>"""
```
Can you give me the version you're using so that I can try and reproduce your problem ?
The variable filename is updated in the state that is specific to the user connected (not in the variable of the main python script)

**Comment by FredLL-Avaiga** [comment]
PS: I didn't see your action:
Indeed, you need to print state.filename
```
def print_filename(state: State):
    print("filename is ", state.filename)
```

**Comment by Dr-Irv** [comment]
Yes, I have to use `state.filename`.  I misunderstood because the docs say "The variable specified in content is populated by a local filename when the transfer is completed."  But it really is the variable within the state that is populated.

**Comment by FredLL-Avaiga** [comment]
We need to fix the doc for this. Tx for reporting it.
