### ISSUE TITLE
Remove Library.get_register_js_function()

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#424]
**Description**

This method may be removed as long as the element's JS name (as set in the constructor, defaulting to a camel case representation of its name) is *always* used.

The JsxParser would receive a full name to process (camel case lib name '.' (?) element js name) and locate the React component name.

The `js_name` argument to the `Element` constructor should become `react_component`.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
name separator will be `_` as `.` is not supported by JsxParser
