### ISSUE TITLE
Decimator: set main trace for charts

### ISSUE THREAD

**Issue by dinhlongviolin1** [Avaiga/taipy-gui#441]
**Description**

Chart can have several traces. To fully support decimator, the user should be able to set the main trace

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
or specify wich decimator for which trace ...
ie decimator as an indexed property => part of the chart config

**Comment by FredLL-Avaiga** [comment]
@dinhlongviolin1 Can you provide here a simple example of decimator use so that I can test the indexed decimator ?
Or do you think it's not a good idea to make decimator an indexed property ?

**Comment by FredLL-Avaiga** [comment]
@dinhlongviolin1 Can you add here an example of a mono trace chart with decimator ?

**Comment by dinhlongviolin1** [comment]
@FredLL-Avaiga you can have a look at this 
https://github.com/Avaiga/front-end-experiments/tree/main/decimator
Let me know if you need anything else

**Comment by FredLL-Avaiga** [comment]
tx
