### ISSUE TITLE
Dynamic property for traces - Charts

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#443]
**Description**
Sometimes, the number of traces in a Dataframe is not known. Thus, it is compulsory to create a Partial to handle it. It is making it a bit complex to use charts this way. The goal would be to simplify this use case of charts.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FlorianJacta** [comment]
We could also extend it to Tables. It seems that there is a need for it.

[Question on the forum on this matter for tables](https://www.taipy.io/forums/topic/reloading-context/)

**Comment by FredLL-Avaiga** [comment]
rebuild for both
