### ISSUE TITLE
BUG-barmode stack doesn't work anymore

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#445]
**Description**
Bars don't appear to be on top of each other when barmode = stack. They are behind each other. This was working under Taipy v1.1 but is not working in Taipy v2.0.

**How to reproduce**
```
from taipy import Gui
import pandas as pd


layout = {"barmode":"stack"}

dict_ = {"x":["t 1","t 2","t 3","t 4"],
         "trace 1":[None,10,None,20],
         "trace 2":[None,40,30,None],
         "trace 3":[20,None,None,10],
         "trace 4":[15,None,None,None]}

data = pd.DataFrame(dict_)

Gui("<|{data}|chart|layout={layout}|x=x|y[1]=trace 1|y[2]=trace 2|y[3]=trace 3|y[4]=trace 4|type=bar|>").run(port=4999)
```

**Expected behavior**
Bars are behind each other when they should be on top of each other.

**Screenshots**
![newplot(15)](https://user-images.githubusercontent.com/98709993/193847114-d3d476c6-cc8f-4d80-ad31-f94937eac07c.png)

**Runtime environment**
Taipy v2.0

**Comment by FredLL-Avaiga** [comment]
Indeed, this is a regression linked to the Gantt like chart
