### ISSUE TITLE
BUG-Missing file demo.py in doc/extension/

### ISSUE THREAD

**Issue by ed-rhilbert** [Avaiga/taipy-gui#450]
**Description**
The file ``demo.py`` is missing in the ``doc/extension``  folder.

**Comment by FabienLelaquais** [comment]
That is due to
`demo*.*` appearing in .gitignore.
Thanks!

**Comment by ed-rhilbert** [comment]
Thanks to you 😃 
Eager to play with these new extension capabilities !
