### ISSUE TITLE
Need to get the nbins property of histograms to work

### ISSUE THREAD

**Issue by vhfgosselin** [Avaiga/taipy-gui#456]
**Description**
A complete and clear description of the the problem is.

**How to reproduce**
A code fragment
```
'''
import numpy as np
from taipy import Gui
import pandas as pd

list_r = np.random.randint(1,50,500)
df = pd.DataFrame(list_r,columns=['value'])
print(df)
page = '''
# first page
<|{df}|chart|type=histogram|y=value|nbins=5|>
'''
Gui(page=page).run()
'''
```

**Expected behavior**
When setting the property nbins=5, it should set the number of bins to be 5.
Currently, it stays at 10.

**Comment by FredLL-Avaiga** [comment]
Hi @vhfgosselin 
This can be handled via the options property

```
import numpy as np
from taipy.gui import Gui
import pandas as pd

list_r = np.random.randint(1,50,500)
df = pd.DataFrame(list_r,columns=['value'])
options={"nbinsx":5}
page = '''
# first page
<|{df}|chart|type=histogram|y=value|options={options}|>
'''
Gui(page=page).run(use_reloader=False, async_mode="threading")
```

PS: I coulnd't find nbins on plotly.js but I found [nbinsx](https://plotly.com/javascript/reference/histogram/#histogram-nbinsx) (and nbinsy)
