### ISSUE TITLE
BUG-notify fails to appear

### ISSUE THREAD

**Issue by mshell99** [Avaiga/taipy-gui#458]
**Description**
notification fails to appear in browser. notify is called twice in callback which otherwise is proeprely executed. No errors/warings in onsole.

**How to reproduce**
Full application code attached here.  Build app from requirements.txt.  Create a scenario (default settings OK). Go to "orders" page and click the "run scenarios" button at bottom of page.  If CPlex is not installed, comment out line 103 of main.py (call to solve) 

**Expected behavior**
2 notifications should appear, one at start of optimization one at end
**Screenshots**
[Shopping.zip](https://github.com/Avaiga/taipy-gui/files/9766259/Shopping.zip)

**Comment by mshell99** [comment]
When I run this in Ubuntu VM,, second notification appears but not first

**Comment by FredLL-Avaiga** [comment]
Can you share a piece of code ?
Are youusing the `with`  syntax ?

**Comment by FredLL-Avaiga** [comment]
@mshell99 Can you try specifying async_mode="threading" as a Gui.run parameter ?

**Comment by FredLL-Avaiga** [comment]
similar to [#493](https://github.com/Avaiga/taipy-gui/issues/493)

**Comment by mshell99** [comment]
When I use async_mode="threading" the notify appears correctly
