### ISSUE TITLE
Table editing -- needs improvement or at least better documentation

### ISSUE THREAD

**Issue by mshell99** [Avaiga/taipy-gui#465]
Documentation indicatese that editable global property defaults to False.  Actually default is true if on_edit property is present. This is essentially redundant.  Two suggestions:
1. Eliiminate global "editable" use presence of on_edit to determine editability.  editable{column(s)] would indicate editable columns, not editable[columns] would indicate columns excluded from editability
2. Keep global editable (and editable[col(s)]) and have global on_edit callback that would be invoked if not explicitly included (like global on_action, on_change)

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
@FabienLelaquais What do you think of a default on_edit callback ?

**Comment by FredLL-Avaiga** [comment]
I don't think we want to remove "global" editable.
It sets a default (and dynamic) editable property for all columns.
It is very convenient when used with editable[col] to set a default that is overridden by column, ie
- define a subset of non editable column : `|editable|not editable[col]|on_edit=...|`
- define a subset of editable column : `|not editable|editable[col]|on_edit=...|`

**Comment by FredLL-Avaiga** [comment]
Changed the doc for editable to default: True

**Comment by mshell99** [comment]
Concerned that these combos of editable and not editable on the same control are confusing
