### ISSUE TITLE
GuiSection API and its usage in taipy config are not aligned.

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-gui#469]
**Severity**
A customer is blocked.

**Bug Description**
When migrating ITM project from 1.1 to 2.0 a bug appeared. Here is a small reproduction of the bug.
The following code throws an error when reading the config while it should be valid: 
```
from taipy.config._toml_serializer import _TomlSerializer

config = '[TAIPY]\n\n[JOB]\n\n[gui]\n\n'

if __name__ == "__main__":
    _TomlSerializer._deserialize(config)

```

```
Traceback (most recent call last):
  File "C:\Users\jeanrobin\workspace\daily-min-temperature\versionning use cases\plop.py", line 7, in <module>
    toto = _TomlSerializer._deserialize(config)
  File "C:\Users\jeanrobin\.virtualenvs\milestone\lib\site-packages\taipy\config\_toml_serializer.py", line 96, in _deserialize
    return cls.__from_dict(cls._pythonify(dict(toml.loads(config_as_string))))
  File "C:\Users\jeanrobin\.virtualenvs\milestone\lib\site-packages\taipy\config\_toml_serializer.py", line 114, in __from_dict
    config._unique_sections[section_name] = section_class._from_dict(sect_as_dict, None, None)
TypeError: _register_gui_config.<locals>._GuiSection._from_dict() takes 2 positional arguments but 4 were given

Process finished with exit code 1
```

**Explanation**

_GuiSection._from_dict inherits from an abstract method. Here is the current signature implemented in taipy-gui : 
`def _from_dict(cls, as_dict: t.Dict[str, t.Any]):` while taipy-config expects the following signature:
`def _from_dict(cls, as_dict: t.Dict[str, t.Any], id, config):`

**Solution proposed**
Change the method's signature by adding id and config params (with None default values: `def _from_dict(cls, as_dict: t.Dict[str, t.Any], id=None, config=None):`) even if they are not used, so it matches the general usage in taipy-config.

**Side note**
The class `_GuiSection` is hidden and local to a function. However, it is the return type of the public method `TaipyConfig.configure_gui`. I believe the `_GuiSection` should be public and documented or the `configure_gui` method should not be exposed.

**Comment by FlorianJacta** [comment]
This issue could be quite urgent depending on the customer. They were trying to update their version of Taipy 1.1 to 2 and will face this issue last week on their own.
