### ISSUE TITLE
BUG- Substituting a variable value in a markdown header doesn't work

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-gui#477]
**Description**

If you want to use a markdown `##` header and want the text to depend on a variable, it doesn't keep the font of the header for the substituted text.

**How to reproduce**
A code fragment
```python
from taipy import Gui


page = """
## Header <|{somevar}|>\
\n
Some text <|{somevar}|>
\n
"""

if __name__ == "__main__":
    somevar = "This should be bold in header, normal in text"
    Gui(page=page).run()
    
```

**Expected behavior**
The text on the header line should all be in the same font

**Screenshots**
![image](https://user-images.githubusercontent.com/15113894/198624992-7b6c8436-544a-43c9-b67f-494b0b2e3924.png)

**Runtime environment**
Please specify relevant indications.
 - OS: Windows 10
 - Browser: Chrome 106.0.5249.119

**Comment by FredLL-Avaiga** [comment]
Added a raw boolean property that forces the render to a simple &lt;span&gt;
