### ISSUE TITLE
BUG- timeout and simultanous notify when async_mode default value 

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#493]
**Description**
Notify are being shown simultaneously even if time passes between two 'notify' in the code.
Functions that work with `async_mode="threading"` are in timeout with async_mode default. The page is not actualized.

**How to reproduce**
```
from taipy.gui import Gui, notify

import time

sleep_value = 1

md = """
<|{sleep_value}|number|>

<|Wait|button|on_action=wait|>
"""

def wait(state):
    notify(state,'i', 'First')
    time.sleep(state.sleep_value)
    notify(state,'i', 'Last')
    
Gui(md).run()
```

**Expected behavior**
Notifications should happen in real-time, corresponding to the time they are sent in the code.
Functions that work with `async_mode="threading"` should also work with the default value of _async_mode_.

**Comment by FredLL-Avaiga** [comment]
similar to [#458](https://github.com/Avaiga/taipy-gui/issues/458)

**Comment by FredLL-Avaiga** [comment]
Can you try :
- Not specify async_mode (=> gevent)
- add this at the beginning of your main script
```
from gevent import monkey
    monkey.patch_all()

```
