### ISSUE TITLE
[table] Columns property ignored?

### ISSUE THREAD

**Issue by gmarabout** [Avaiga/taipy-gui#521]
**Description**
Creating a table based on an array, the columns header property looks ignored.

**How to reproduce**

```
from taipy.gui import Gui

data = [["Greg", "Montpellier", "France"], ["Bill", "Seattle", "USA"]]

page = """
<|{data}|table|columns=Name,City,Country|>
"""

Gui(page=page).run(port=8000)

...
```
The result is the following (notice the missing columns headers):
<img width="1437" alt="Screenshot 2022-12-05 at 11 44 57" src="https://user-images.githubusercontent.com/26060559/205618399-ab043844-6ef9-4302-9c87-eda0e7133536.png">

**Expected behavior**
Should have "Name", "City" and "Country"  as column headers.

**Runtime environment**
 - OS: MacOS 13.0.1
 - Browser: Chrome
 - Python 3.10.5

**Comment by FredLL-Avaiga** [comment]
columns property is a list of the column names as they appear in the data set
In this example the dataset being an array, column names are the indexes.
Column title can be specified by passing a dict as column property
{"0": {"title": "Name"} ...}

**Comment by gmarabout** [comment]
Indeed! Thank you @FredLL-Avaiga !
For the record, here is the working version:

```
from taipy.gui import Gui

data = [["Greg", "Montpellier", "France"], ["Bill", "Seattle", "USA"]]
columns = {"0": {"title": "Name"}, "1": {"title": "City"}, "2": {"title": "Country"}}
page = """
<|{data}|table|columns={columns}|>
"""

Gui(page=page).run(port=8000)
```
