### ISSUE TITLE
:sparkles: Have the ability to select rows in table

### ISSUE THREAD

**Issue by gmarabout** [Avaiga/taipy-gui#522]
**What would that feature address**
It would be useful to be able to select rows in a Taipy table, even if the table is not editable.

***Description of the ideal solution***
* Have a "selection_mode" property with possible values: None (the default), single_row, multiple_rows.
* Have a callback function to be called on "selection changed" event
* Should be linked to the same property value as the existing "selected" property

***Caveats***

***Other options***
* one can add a boolean field on row object, but:
* can be editable only if the whole table is editable (which is not always what we want)
* is currently shown as a toggle (would expect a check box)

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
To allow edition of only one column, you can specify `|not editable|editable[boolean column name]|`
But I'll add an on_action property (mono selection for now)

**Comment by gmarabout** [comment]
Thanks, but can you give an example of what is expected for `|editable[boolean column name]|` ?

**Comment by FredLL-Avaiga** [comment]
some properties can be indexed by column name.
editable is one of them:
- editable without [...] applies to the whole table
- editable with [a column name] applies only the specified column
