### ISSUE TITLE
:bug: Row index given in table callbacks is not global

### ISSUE THREAD

**Issue by gmarabout** [Avaiga/taipy-gui#524]
**Description**
When using table callbacks (`on_delete`, `on_edit`), the payload provides the index of the row where the action occurred.
However, the index given is local to the current page, and not global.
As a consequence, it is difficult to retrieve the actual row data. 

**How to reproduce**

```
from taipy.gui import Gui


def on_row_delete(state, var_name, action, payload):
	# Get the row index from the 'payload':
	row_index = payload["index"]
	print(f"On row delete: {row_index}")


data = [[f"Name {i}", f"City {i}", f"Country {i}"] for i in range(1000)]

columns = {"0": {"title": "Name"}, "1": {"title": "City"}, "2": {"title": "Country"}}
page = """
<|{data}|table|columns={columns}|on_delete={on_row_delete}|>
"""

Gui(page=page).run(port=8000)

```

- Run the code here-above.
- Move to another page (not first page)
- Click on the delete button and validate
- The console shows the index of the row. But the index is local to the page, not global: `On row delete: 9`.
 
**Expected behavior**
-  We would expect the payload to provide enough information to identify the underlying row data.

**Runtime environment**
 - OS: MacOS 13.0.1
 - Browser: Chrome
 - Python 3.10.5

**Comment by FredLL-Avaiga** [comment]
Can't replicate this issue
Python console gives: `On row delete: 214`

**Comment by gmarabout** [comment]
I am using Taipy `taipy-gui-2.1.0.dev0` directly from the source (`develop` branch).
I have installed this version using:
* `cd gui ; npm install ; npm run build`
* `pip install .` (notice that `pip install -e .` does not work at all because of some dependency issue with `taipy-config`).

**Comment by FredLL-Avaiga** [comment]
I beleive npm run build would fail if you didn't add the option npm install --omit=optional

**Comment by gmarabout** [comment]
Actually, the build indicated a success:
`webpack 5.75.0 compiled with 2 warnings in 14667 ms`.

But indeed, looking at the the traces, there have been some failures...

**Comment by FredLL-Avaiga** [comment]
or you can use npm run inst install of npm install

**Comment by gmarabout** [comment]
Did a full recompile with `npm run build --omit=optional` and reinstalled the python package using `pip install .`, run the script here above... same result :-(

**Comment by gmarabout** [comment]
Did the following:
* `rm node_modules` to begin with a fresh start
* `npm install --omit=optional`
* `npm run build`
* `pip install .`
And now the bug does not occur anymore.
Thanks.

**Comment by FredLL-Avaiga** [comment]
a bit of doc improvement...
