### ISSUE TITLE
:bug: BUG-Using the `style` table property causes the table to stop displaying

### ISSUE THREAD

**Issue by gmarabout** [Avaiga/taipy-gui#528]
**Description**
When using the `style` property as described (here)[https://docs.taipy.io/en/latest/manuals/gui/viselements/table/#show-a-table], the table stops displaying and the console displays a Web socket warning:  

```
UserWarning: Exception raised in Web Socket communication in '<module>':
'<' not supported between instances of 'str' and 'int'
```

**How to reproduce**

```
from taipy.gui import Gui

data = [["Item1", True], ["Item2", True], ["Item3", False]]
columns = {"0": {"title": "Name"}, "1": {"title": "Activated"}}

page = """
<|{data}|table|style={lambda state, idx, row: "red-row" if idx % 2 == 0 else "blue-row"}|columns={columns}|>
"""

Gui(page=page).run(port=8000)
```
Run the above code.
  - Notice that the presence of an style sheet does not change the behaviour

The view is the following: 
<img width="1524" alt="Screenshot 2022-12-08 at 10 24 15" src="https://user-images.githubusercontent.com/26060559/206408780-c198b5a1-911f-4768-892a-cb1114b135c5.png">

The console:
```
UserWarning: Exception raised in Web Socket communication in '<module>':
'<' not supported between instances of 'str' and 'int'
```

...

**Expected behavior**
* The style is applied
* The table displays properly

**Runtime environment**
 - OS: MacOS
 - Browser: Chrome
 - Python 3.10.5

**Comment by FredLL-Avaiga** [comment]
this happens when columns don't have name (index is used) 
And we need to add a new column (which has a name)
The json encoder tries to sort the keys of the row object which is not necessary and time consuming.
