### ISSUE TITLE
BUG-Display bug when a table is lazily populated

### ISSUE THREAD

**Issue by gmarabout** [Avaiga/taipy-gui#529]
**Description**
If a table starts empty, and then populated after a callbacl/action by modifying the state,
the table may not display properly.
Refresing the page will then display the table well.

**How to reproduce**

```
from taipy.gui import Gui

data = []
columns = {"0": {"title": "Name"}, "1": {"title": "Activated"}}


def load_data(state):
    print("Clicked!")
    state.data = [[f"name {i}", True] for i in range(1000)]


page = """
<|{data}|table|columns={columns}|>
<|Load Data|button|on_action=load_data|>
"""

Gui(page=page).run(port=8000)
```

- Run the script
- The table stats "empty" since the `data` is an empty array
- Click the button which calls `load_data`
- See the table display
- Refresh the page for a good display

Initial state (OK):
<img width="1524" alt="Screenshot 2022-12-08 at 10 36 31" src="https://user-images.githubusercontent.com/26060559/206411406-e6122898-08ca-4728-93fe-c8ef48477f12.png">

After clicking the button (Not OK):
<img width="1524" alt="Screenshot 2022-12-08 at 10 36 08" src="https://user-images.githubusercontent.com/26060559/206411498-5bfa430c-bc9a-48be-9a8b-0a017dc3dfa5.png">

After refreshing the page (now OK):
<img width="1524" alt="Screenshot 2022-12-08 at 10 36 13" src="https://user-images.githubusercontent.com/26060559/206411549-2bfb0a1e-eb1e-47da-b2fb-38e91305e8af.png">

**Expected behavior**
The table should always display properly

**Runtime environment**
Please specify relevant indications.
 - OS: MacOS
 - Browser: Chrome
 - Python 3.10.5

**Comment by FredLL-Avaiga** [comment]
Not sure we'll fix this one as the columns definition is static and calculated at the first render.

**Comment by gmarabout** [comment]
Hello @FredLL-Avaiga 👋🏻 
Thank you for your feedback. 
However, I don't think we should rely on the fact that a table would always be initially populated. The use-case where the table starts "empty" does not look that exotic to me...

**Comment by FredLL-Avaiga** [comment]
you could have an empty dataframe/dict with defined columns
