### ISSUE TITLE
:bug: BUG-Cannot sort table using Python lists

### ISSUE THREAD

**Issue by gmarabout** [Avaiga/taipy-gui#530]
**Description**
Using a table bound to a Python list for its data, the sort would not work.

**How to reproduce**
```
from taipy.gui import Gui

data = [[f"Name {i}", i % 3 == 0] for i in range(1000)]
columns = {"0": {"title": "Name"}, "1": {"title": "Activated"}}


page = """
<|{data}|table|columns={columns}|>
"""

Gui(page=page).run(port=8000)
```
 - Execute the script here about (using the latest `develop` version)
 - Try sort a column by clicking on its header
 Log in the console:
```
UserWarning: Decoding Message has failed: {'type': 'DU', 'name': '_TpD_tpec_TpExPr_data_TPMDL_1', 'payload': {'start': 0, 'end': 100, 'orderby': '1', 'sort': 'desc', 'aggregates': [], 'styles': {}, 'handlenan': False, 'filters': [], 'columns': ['0', '1'], 'pagekey': '0-100-0,1-1-desc'}, 'propagate': True, 'client_id': '20221128162535407204-0.7325782016898321', 'ack_id': 'e2dbe19c-37e0-4136-8e14-c370b76819e7', 'module_context': '__main__'}
'1'
```
**Expected behavior**
* The sort works
* No error in the console

**Runtime environment**
Please specify relevant indications.
 - OS: MacOS
 - Browser: Chrome
 - Python 3.10.5
 - Taipy 2.1.0.dev0

**Comment by FredLL-Avaiga** [comment]
link to the columns not having name thus we use index.
