### ISSUE TITLE
BUG- Cannot style individual cells of a table

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-gui#557]
**Description**
The docs indicate that for a table, you can style individual cells by using `style[_colname_]=`, but the result is that cells are styled by row.  Secondly, there is an issue that the actual parameters passed to the styling function are different than what is documented.

**How to reproduce**

```python
import pandas as pd

from taipy import Gui
from taipy.gui import State

df = pd.DataFrame.from_records(
    [["yellow", "green"], ["red", "blue"]], columns=["A", "B"]
)


def rowstyle(
    state: State, value: str, index: int, rowcontents: pd.Series, colname: str
) -> str:
    print("index ", index, " colname ", colname, " value ", value)
    return value + "-cell"


lambda_ref = "{lambda state, value, index, rowcontents, colname: rowstyle(state, value, index, rowcontents, colname)}"

page = (
    "<|{df}|table|width=400px|show_all=True"
    + "|style[A]="
    + lambda_ref
    + "|style[B]="
    + lambda_ref
    + "|>"
)

if __name__ == "__main__":
    Gui(page=page, css_file="styletst").run(
        dark_mode=False,
    )
```

with CSS file called `styletst.css`:
```css

.yellow-cell {
    background-color: yellow;
}

.red-cell {
    background-color: red;
}

.green-cell {
    background-color: green;
}

.blue-cell {
    background-color: blue;
}
```

**Expected behavior**
The table should display with different colors for each of the cells.

Also note that by introspection, there were 5 arguments passed to the `rowstyle` function, with the 4th argument being a `Series` corresponding to the row, and the 5th argument being the column name.  The docs say there are 4 arguments.

**Screenshots**
![image](https://user-images.githubusercontent.com/15113894/210115967-d640ff27-b91b-4085-b6da-dc964f30874b.png)

Since the value of the cell drives the color, the table should have 4 different colored cells.  It seems only the last column is used.

**Runtime environment**
Please specify relevant indications.
 - OS:  Windows 10
 - Browser: Chrome latest
Using following versions:
```text
# Name                    Version                   Build  Channel
taipy                     2.0.0                    pypi_0    pypi
taipy-config              2.0.1                    pypi_0    pypi
taipy-core                2.0.3                    pypi_0    pypi
taipy-gui                 2.0.2                    pypi_0    pypi
taipy-rest                2.0.0                    pypi_0    pypi
```

**Comment by Dr-Irv** [comment]
It seems that the solution here is to have a lambda function that is unique for each column.  Internally, you are using the parameters of the lambda function and the corresponding function call as a string identifier for the column modification, and in the original example, those strings are the same. 

I fixed this by appending the column name to the parameter of the style function, as shown below:
```python
import pandas as pd

from taipy import Gui
from taipy.gui import State

df = pd.DataFrame.from_records(
    [["yellow", "green"], ["red", "blue"]], columns=["A", "B"]
)


def rowstyle(
    state: State,
    value: str,
    index: int,
    rowcontents: pd.Series,
    colname: str,
    real_colname: str,
) -> str:
    print(
        "index ",
        index,
        " colname ",
        colname,
        " value ",
        value,
        " real_colname ",
        real_colname,
    )
    return value + "-cell"


def get_lambda_ref(colname: str):
    return (
        "{lambda state, value, index, rowcontents, colname: rowstyle(state, value, index, rowcontents, colname, '"
        + colname
        + "')}"
    )


page = (
    "<|{df}|table|width=400px|show_all=True"
    + "|style[A]="
    + get_lambda_ref("A")
    + "|style[B]="
    + get_lambda_ref("B")
    + "|>"
)

if __name__ == "__main__":
    Gui(page=page, css_file="styletst").run(
        dark_mode=False,
    )
```

I think you need to document this technique, or fix the code in some way so people can use one function for all of their columns.

**Comment by FredLL-Avaiga** [comment]
The correct documentation should be
- `style[_column_name_]`: this applies to a specific cell.
     The given function expects five optional parameters:
     - _state_: the current state
     - _value_: the value of the cell
     - _index_: the index of the row of this cell
     - _row_: all the values for this row
     - _column_name_: the name of the column for this cell

**Comment by FredLL-Avaiga** [comment]
And this code will give each td a class with "{value}-cell" and each tr a class with "row-{index}"

import pandas as pd

```
from taipy.gui import Gui, State

df = pd.DataFrame.from_records(
    [["yellow", "green"], ["red", "blue"]], columns=["A", "B"]
)


def colstyle(
    state: State, value: str, colname: str
) -> str:
    print("colname ", colname, " value ", value)
    return value + "-cell"

def rowstyle(
    state: State, index: str, row: str
) -> str:
    print("index ", index, " row ", row)
    return f"row-{index}"

page = (
    "<|{df}|table|width=400px|show_all=True"
    + "|style=rowstyle"
    + "|style[A]=colstyle"
    + "|style[B]=colstyle"
    + "|>"
)

if __name__ == "__main__":
    Gui(page=page, css_file="styletst").run(
        dark_mode=False,
    )
```

**Comment by FredLL-Avaiga** [comment]
fixed the internal column name
