### ISSUE TITLE
BUG-Data specification in charts is not homogeneous

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#562]
**Description**

If you use an array of dicts in the `data` property in a chart control, on cannot create the array on the fly, in the control definition.

That is:

If you have:
```
d1 = { ... }
d2 = { ... }
d = [d1, d2]
```

Then in the Markdown definition:
```
<|{d}|chart|...|>
```
will work, but
```
<|{[d1,d2]}|chart|...|>
```
will break (with a very cryptic message).

**How to reproduce**

Here is some code that reproduces the problem:
```
from taipy.gui import Gui

x = list(range(10))
y1 = x
y2 = list(reversed(x))

data1 = {
    "x": x,
    "y": y1
}
data2 = {
    "x": x,
    "y": y2
}

data = [data1, data2]

properties = {
    "x[1]": "0/x",
    "y[1]": "0/y",
    "x[2]": "1/x",
    "y[2]": "1/y",
}

page = """
<|{data}|chart|properties={properties}|>

*|{[data1,data2]}|chart|properties={properties}|*
"""

Gui(page).run(run_browser=False)
```

If you replace the control definition by the second (kinf-of commented out), the application breaks on its first display.

**Expected behavior**
Both control definitions should behave the same way.

**Comment by FredLL-Avaiga** [comment]
dict are transformed into _MapDict but array are left alone
