### ISSUE TITLE
BUG-Navbar lov ordering

### ISSUE THREAD

**Issue by aazimh** [Avaiga/taipy-gui#563]
**Description**

I have an app with multiple pages and I'm looking to add a navbar element, which automatically uses the pages registered if no list is given. When I use the following code:

`<|navbar|>`

it seems to order the pages alphabetically, which does not work for my use case (my pages are `Home`, `Forecast`, and `Parameters` where `Home` always needs to be first obviously, but at the moment `Forecast` automatically takes the first spot. 

Functionally, this navbar works fine: clicking each element opens the relevant page in the same tab, and the current page is always highlighted correctly.

What I tried to do to force the order was to use the `lov` parameter, like so:

`<|navbar|lov={[("home","Home"), ("forecast","Forecast"), ("params","Params")]}|>`

This fixes the order issue, but introduces some weird quirks in functionality:

- The current page I'm on is not highlighted in the navbar (it's always `Home` that appears selected)
- Clicking any page via the navbar opens it in a new tab (the documentation says this will happen if the IDs begin with http, but that is not the case here)

**How to reproduce**

This is how my pages are registered:

```
from pages.params import params_page
from pages.forecast import forecast_page
from pages.home import home_page

pages = {
    'forecast' : forecast_page,
    'home': home_page,
    'params' : params_page
    }

Gui(pages=pages).run(async_mode="threading",use_reloader=True, debug=True, watermark="", dark_mode=True)

```

My app setup is a `main.py` file (with the above lines + other functions that are not relevant), and a `pages` folder with `pages\forecast.py`, `pages\home.py` and `pages\params.py` all imported into the main file as shown.

**Expected behavior**

A navbar with the intended forced order of items, that updates to highlight the current page, and does not open pages in new tabs.

**Runtime environment**
Please specify relevant indications.
 - OS: [e.g. Linux, Windows] and version - Windows 10
 - Browser: [e.g. Chrome, Edge, Safari] and version - Chrome 108.0.5359.125 (Official Build) (64-bit) (cohort: Stable) 
and any other relevant information.

I'm aware I might be using the navbar parameters incorrectly, so would be great to get some help on how I can basically force the order of items without changing any of the functionality - thank you!

**Comment by FabienLelaquais** [comment]
Hi Aazim,

and thank you for your feedback.

I just gave this code a try:
```
from taipy.gui import Gui

pages = {
    "/": "<|navbar|>",
    'home' : "# Home page",
    'forecast' : "# Forecast page",
    'params' : "# Params page",
    }

Gui(pages=pages).run()
```

Basically, your very code, with the root page ("/") added with the `navbar` you want.
What I can see is that the order is preserved, and no new tab or new window is created when I select a page.

![issue#563](https://user-images.githubusercontent.com/86590727/211062899-20350144-401c-46d2-a56c-95091fd40bdb.png)

Can you check on your side?

What version of Taipy are you using?

Thanks.

**Comment by FabienLelaquais** [comment]
Hi Aazimh and thank you for your feedback.

We reproduce your problem with the latest version of the Taipy GUI package, and this code:

```
from taipy.gui import Gui

pages = {
    "/": '<|navbar|lov={[("home","Home"), ("forecast","Forecast"), ("params","Params")]}|>',
    'home' : "# Home page",
    'forecast' : "# Forecast page",
    'params' : "# Params page",
    }

Gui(pages=pages).run(async_mode="threading",use_reloader=True, debug=True, watermark="", dark_mode=True)
```

We are looking at this.

Thank you

**Comment by FabienLelaquais** [comment]
You can fix your program by prepending '/' to all the page names:
```
from taipy.gui import Gui

pages = {
    "/": '<|navbar|lov={[("/home","Home"), ("/forecast","Forecast"), ("/params","Params")]}|>',
    'home' : "# Home page",
    'forecast' : "# Forecast page",
    'params' : "# Params page",
    }

Gui(pages=pages).run(async_mode="threading",use_reloader=True, debug=True, watermark="", dark_mode=True)
```
That would work properly.


![issue#563](https://user-images.githubusercontent.com/86590727/211064588-02caafeb-0eb8-48d7-9b60-9e1fe450b284.png)

The doc is wrong, however. The page opens in a new tab if... it's identifier does not start with '/'.

Thanks.

**Comment by aazimh** [comment]
Thank you @FabienLelaquais! I partially used your fix, and it seems to have worked, but I'm not clear how/why it worked.

All I did was add a `/` before my page names in the navbar definitions **in the Markdown on each specific page**. 

However, you also have added the navbar as the root `/` page in the `pages` definition itself like so:

```
pages = {
    "/": '<|navbar|lov={[("/home","Home"), ("/forecast","Forecast"), ("/params","Params")]}|>',
...
```

This is throwing me off and it's something I have not done, as to me it indicates the root URL would just redirect to a navbar? Is that all it would do, or is this standard practice for using a navbar? i.e. it needs to be added to the Markdown of each individual page, AND to the `pages` dictionary at the root URL?

Thank you for the help though, it has solved the problem :) now I just want to complete my understanding of how it works.

**Comment by FabienLelaquais** [comment]
You actually should not have more than one place where the navbar is defined.
That would be in the root page (the one registered as '/'). And in the root page only. The provided code shows how to do that.
This code has no navbar anywhere but in that page.
May be the [Root page](https://docs.taipy.io/en/latest/manuals/gui/pages/#root-page) section of the doc would clarify things...

It actually is standard practice to have some sort of a 'main' page that holds all common GUI items (like a banner, a footer, ... and a navbar).

Just close that issue when you think you're good!
Cheers,

**Comment by aazimh** [comment]
@FabienLelaquais Got it, that was a fundamental misunderstanding on my part so thank you for clearing that up! I actually hadn't seen that particular part of the documentation. 

Doing it this way also has the added benefit of not reloading the page and having a smooth transition between navbar elements (this is mentioned in the documentation you linked but I had no idea) so it's a win-win :) thank you again!
