### ISSUE TITLE
Forcing the WebApp location

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#564]
**Description**

As of now, the WebApp is built from the [root]/gui directory, and produces a set of JavaScript bundles and other assets in [root]/src/taipy/gui/webapp.
This is exposed as `taipy/gui/webapp` when the package gets installed.

When developers want to work exclusively on the front-end side of things, they have to install the whole taipy-gui package over and over to watch their changes or debug their code.

It would be far easier to let developers indicate where the JS bundles should be found, independent from the Python code of Taipy GUI, in a way similar to other runtime configuration for GUI.

I propose that we use:
* a configuration entry called `webapp_path` that can be set to the full path of the directory where bundles are created.<br/>
  The default would be [taipy_root]/taipy/gui/webapp.
* this could be overridden by setting the environment variable "TAIPY_GUI_WEBAPP_PATH"
* this can be overridden by a command-line option "--webapp-path/-w"

**Acceptance Criteria**
- [ ] Ensure new code is unit tested
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure change is documented

**Comment by FredLL-Avaiga** [comment]
any possible argument overridden with -w ?
To be on the safe side, I'd propose to not have a short command-line option
