### ISSUE TITLE
BUG-name indexed property does not do what is expected

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#567]
**Description**

It seems that if we use an array as a value for the name property, it is not used properly.

**How to reproduce**

Run this code:
```
from taipy import Gui
data = { "A": [1, 2, 3, 4], "B": [2, 3, 4, 5] }
names  = ["A samples", "B samples"]
Gui('<|{data}|chart|type=histogram|x={["A", "B"]}|name={names}|>').run()
```
And look at the legend.
It should show "A samples" and "B samples". But only "A samples" appears, twice.

Now if, in the chart definition, we use `name[1]=A samples|name[2]=B samples` then the legend shows what is expected.

**Expected behavior**
Not matter what of the two syntaxes for the `name` property value is used, the two distinct strings should appear in the chart legend.

**Comment by FredLL-Avaiga** [comment]
bug linked to the reserved name "name" in enum :-(
