### ISSUE TITLE
Taipy Controls UI improvements

### ISSUE THREAD

**Issue by ghost** [Avaiga/taipy-gui#573]
## Suggestions
About controls

#### file_selector and file_download
Why using a `<Fab/>` (_Floating_ Action Button) component instead of a regular `<Button/>` ? These controls are not used as **floating** (fixed in a viewport angle) buttons, so there is no point using that component for these. Using a `<Button/>` component would improve UI consistency with Taipy `button` controls and avoid the need to manually normalize styles between them.

#### menu
The icons part lacks a way to manage light/dark mode. Right now, inserting a black icon, for instance, looks good in light mode, but as soon as the users goes for dark mode, the black icon contrast with the background becomes way too low. From my point of view, there would be two ways to improve this : 
- In the control parameters, give the possibility to load two icons, one for dark mode, one for light mode.
- Allow SVG icons to be inserted in the DOM as inline SVG to inherit the current theme text color.

#### table
There is an inconsistancy on this control in the way parameters affect styles. The `width` or `height` parameters, for instance, apply to the highest level (as it should, actually), but the `class_name` parameter applies to the HTML `<table>` tag, 2 child levels lower.
Consequently, setting styles and classes on that control (such as a margin-top, for example) may cause an unintended rendering by applying styles into the container when one would intend to set it _around_ it.
The `class_name` parameter should be rendered on the highest level as well.

#### image
The images are currently rendered as a `<span>` element's background-image. Not only is it semantically bad and not accessible for disabled users (such images are not announced by text-to-speech devices) like this, but it also makes it impossible to manipulate image dimensions homothetically or responsively.
To fix these issues altogether, images should be rendered as HTML `<img src="" alt="" />` tags.
_Additional oddity/question : `background-position` has been set to `center 40%`... I don't understand the point of not vertically centering the background in its container as a general rule._

**Comment by FredLL-Avaiga** [comment]
All done, me think
