### ISSUE TITLE
BUG-Multiple upload buttons can't have separate behavior

### ISSUE THREAD

**Issue by AlbVu** [Avaiga/taipy-gui#576]
**Description**
- Taipy GUI uses the behavior of the first file_selector element for all file selectors, and changing the file path of other file_selectors only affects the first one.
- Also, only the on_action function for the first file_selector is called, even when trying to use other file_selectors. 

**How to reproduce**
Code to replicate the issue:
```
from taipy import Gui

path_1=""
path_2=""

page="""
<|{path_1}|file_selector|label = UPLOAD BUTTON 1|on_action=f1|>   
<|{path_2}|file_selector|label = UPLOAD BUTTON 2|on_action=f2|>   

PATH 1: <|{path_1}|>   
PATH 2: <|{path_2}|>   
"""

def f1(state): 
    print("Upload button 1 is used")

def f2(state):
    print("Upload button 2 is used")

Gui(page=page).run()
```

**Expected behavior**
- Upload button 1 works as expected, path_1 variable is changed and f1 is called. 
- Expected the same result for upload button 2, expected changes in path_2 variable and f2 is called.
- Expected separate file_selectors to be independent of each other. 

**Runtime environment**
 - taipy 2.0.0
 - taipy-gui 2.0.4

**Comment by FredLL-Avaiga** [comment]
tx @AlbVu 
workaround: specify an id for each fileselector
