### ISSUE TITLE
BUG- can't dismiss a notification with `taipy.gui.notify(state, "")`

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-gui#581]
**Description**
The docs indicate that passing a notification type of `""` will dismiss the last notification, but that doesn't seem to work.

**How to reproduce**

```python
from taipy import Gui
from taipy.gui import State, notify

result = "UNKNOWN"
notified = False
show_result = False


def checker(state: State):
    if state.result == "Bad":
        notify(state, "error", "You cannot enter 'Bad'", duration=10000)
        return
    else:
        notify(state, "")  # should remove the notification
    state.show_result = True


page = """<|{result}|input|on_action={lambda s: checker(s)}|>

<|part|render={show_result}|

<|Result is|text|>
<|{result}|text|>

|>
"""

if __name__ == "__main__":
    Gui(page=page).run(
        async_mode="threading",
        title="Notify Demo",
        debug=True,
        use_reloader=True,
    )
```

Type in the word `Bad` into the box, and you will get a notification. Then type anything else, and you will see two notifications, the red one and a blue one.

**Expected behavior**
The red notification should disappear.

**Screenshots**

![image](https://user-images.githubusercontent.com/15113894/214411537-eed93b81-65e3-47cf-a94c-8a7f8b4beaf8.png)
**Runtime environment**
Please specify relevant indications.
 - OS: Windows 10
 - Browser: Chrome 109.0.5414.74

**Comment by FlorianJacta** [comment]
Thank you! Indeed, the notification behavior does not reflect what is written in the documentation for the _notify_ function. We will take a look at it.
