### ISSUE TITLE
BUG- strange behaviors of visual elements in the root page

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#583]
**Description**
When put in the root page, visual elements (like _selector_) and their associate variables raise warnings and don't call the _on_change_ function present in the file.

**How to reproduce**
[page_scope.zip](https://github.com/Avaiga/taipy-gui/files/10497547/page_scope.zip)

Run _main.py_ and change the selection of the selector. A warning should appear and the _on_change_ shouldn't be called.

In _main.py_:

```python
from taipy.gui import  Markdown, Gui
from pages import home


selected = None

root_md = Markdown("""
<|navbar|>

<|{selected}|selector|lov={["1", "2", "3"]}|>
""")

def on_change(state, var_name: str, var_value: str):
    print('In on change')

md_pages = {"/": root_md, "home": home.home_md}

Gui(pages=md_pages).run()
```

In _pages/home.py_:
```python
from taipy.gui import Markdown

home_md = Markdown("<|{selected}|>")
```

**Expected behavior**
Changing the selection of the selector shouldn't raise any warning and it should call the _on_change_ function of the file.

**Runtime environment**
Taipy GUI: 2.0 and dev for 2.1

**Comment by FredLL-Avaiga** [comment]
context issue I guess
@dinhlongviolin1 any thought ?

**Comment by dinhlongviolin1** [comment]
I guess so. I will have a look at it. Thanks!

**Comment by FredLL-Avaiga** [comment]
Should this be backported to 2.1 ?
