### ISSUE TITLE
BUG- `selector` with multiple items doesn't respect `width` and doesn't display `label`

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-gui#586]
**Description**
If using the `selector` control, there are 2 problems I have found when you specify  `multiple=True` or `dropdown=False` 
1. If you specify a `label`, the label does not appear
2. If you specify `width`, the width is not respected.

**How to reproduce**
```python
from taipy import Gui

selection1 = []
selection2 = "Item 2"
selection3 = "Item 3"

page = (
    "## Multiple Selection Too Wide Missing Label\n"
    + "<|{selection1}|selector|lov=Item 1;Item 2;Item 3|"
    + "multiple=True|label=Choose Your Item|"
    + "width=300px|>\n"
    + "## Single Selection Just Right With Label\n"
    + "<|{selection2}|selector|lov=Item 1;Item 2;Item 3|"
    + "dropdown=True|label=Choose Your Item|"
    + "width=200px|>\n"
    + "## Single Selection Too Wide Missing Label\n"
    + "<|{selection3}|selector|lov=Item 1;Item 2;Item 3|"
    + "dropdown=False|label=Choose Your Item|"
    + "width=250px|>\n"
)


if __name__ == "__main__":
    gui = Gui(page=page)

    gui.run(
        async_mode="threading",
        title="Multiselector Demo",
        debug=True,
        use_reloader=True,
    )
```

**Expected behavior**
The label should appear, and the width should be respected.

**Screenshots**
![image](https://user-images.githubusercontent.com/15113894/214710258-c41419e3-452e-416d-ba55-5c392c37245e.png)

Note the grey area on the right extends all the way to the right end of the browser.  The width is respected for the elements that you can select, but not for the bounding box.

**Runtime environment**
Please specify relevant indications.
 - OS:  Windows 10
 - Browser: Chrome

**Comment by FlorianJacta** [comment]
Thank you Irv! In fact, it seems that the label is missing only when `dropdown=False`. This visual element will show the correct label:

`<|{selection4}|selector|lov=Item 1;Item 2;Item 3|dropdown|multiple|label=Choose Your Item|>`

![multiple_selection](https://user-images.githubusercontent.com/98709993/214793935-f5a06298-5e5f-42ea-adfe-ede1f20a1513.png)

**Comment by Dr-Irv** [comment]
> Thank you Irv! In fact, it seems that the label is missing only when `dropdown=False`. This visual element will show the correct label:

Thanks.  I can use that in the demo I'm working on.  Also, `dropdown=True` removes the width problem, so both the `width` and missing label are issues with `dropdown=False`.

**Comment by FlorianJacta** [comment]
Exact!
