### ISSUE TITLE
Visual element property shortcut

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#601]
**Description**

Especially in charts, there are a handful of properties that use dictionary values that are used with a syntax that looks like:
```
    <|{data}|chart|layout={layout}|options={options}|>
```

We can see a pattern here: we could leverage the variable name to deduce the property name.

**Proposition**

In the visual element parser, we could detect property.value fragments that look like `{name[_suffix]}` where `name` is a property name and `name_suffix` is a variable.
The parser would then generate the equivalent to `name={name_suffix}` (or `name={name}` if there is no suffix).

If there is no suffix, it should work as well, so that the syntax mentioned above would be:
```
    <|{data}|chart|{layout}|{options}|>
```

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
Let's forget that suffix stuff :-)

**Comment by FabienLelaquais** [comment]
That indeeds needs the parser to know about control type names and their respective properties.
Can be in another issue, somehow correlated but even less important.
