### ISSUE TITLE
BUG-Charts properties documented with unprocessed Markdown markup

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#604]
**Description**

Because the json file that contains the visual elements document contain some Markdown text, the documentation for some control properties is not rendered properly in the final doc.

**How to reproduce**

See for example the `lon` property of the `chart` control.

**Expected behavior**

No weird text in the chart properties table.

**Comment by FredLL-Avaiga** [comment]
https://docs.taipy.io/en/latest/manuals/gui/viselements/chart/#properties

I suppose we have to move them from `[text](url)` to `<a href="url">text</a>` ?
