### ISSUE TITLE
BUG-Throbber always running using long callbacks

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#610]
**Description**
After an `invoke_long_callback`  call, the Taipy GUI wheel is always running even if the execution is finished.

**How to reproduce**
```python
from taipy.gui import Gui, Markdown, invoke_long_callback, notify

import time


def heavy_fct():
    time.sleep(5)
    return 0

def heavy_status(state, status):
    if isinstance(status, bool):
        if status:
            notify(state, 'success', "Finished")
        else:
            notify(state, 'error', f"An error was raised")
    
def on_action(state):
    invoke_long_callback(state,
                         heavy_fct, [],
                         heavy_status, [],
                         2000)  
        
page = Markdown("<|Run long|button|on_action=on_action|>")


Gui(page).run()
```

**Expected behavior**
At the end of the execution of the long callback, the wheel should disappear.

**Screenshots**
![wheel](https://user-images.githubusercontent.com/98709993/219021619-597eae4f-fc45-444a-a77f-0bab7bda426a.png)

**Runtime environment**
Taipy GUI 2.1.0

**Comment by FredLL-Avaiga** [comment]
This is true also for any action that doesn't change any variable.

**Comment by FredLL-Avaiga** [comment]
We could shut it down after 10 secs ...
Or we could force an update from the backend after calling the action ...
@FabienLelaquais What do you think ?

**Comment by FabienLelaquais** [comment]
I think this a a two-fold question:
- In my mind, the throbber should go away as soon as the callback exits.
- Now in the long callbacks situation, this makes no sense: the action, from the backend standpoint, is immediate, since the real job is performed in another thread. And... in my mind.. this is fine: the user should not be able to do anything in the UI when the backend is busy. But free to when the backend is available, which is almost immediate in the long callback case.

**Comment by FredLL-Avaiga** [comment]
Then we need to force an update BE->FE after each action ...
It's a bit costly for a "nice to have" feature ...

**Comment by FabienLelaquais** [comment]
Like an 'action done' message?
That we would shortcircuit in the long callback case?

**Comment by FredLL-Avaiga** [comment]
FE doesn't know about long callbacks
In case of long callbacks, the UI feedback is the responsibility of the user-code

**Comment by FabienLelaquais** [comment]
Yes yes I do understand this.
The only person that knows about long callbacks is the developer.
So some magic call can be perform (we have the notifications in the API for this) when everything is done...
