### ISSUE TITLE
Allow redirecting user to an external site

### ISSUE THREAD

**Issue by aazimh** [Avaiga/taipy-gui#621]
**What would that feature address**
Description of the lacking functionality that this issue would address.

I am currently trying to develop an application that involves a user having to log in to their Google account. This involves getting an 'authorization URL' from Google that the user needs to be redirected to. Ideally I would do this automatically, but I cannot figure out if this is possible in Taipy at all. Another alternative would be to just display the URL to the user for them to click, but I can only figure out how to display it as text, not a clickable link, and this isn't great UX. I found the 'navigate' function within Taipy (wasn't easy to find) but that seems to only be limited to pages in the application.

***Description of the ideal solution***
What would be the best way to provide that functionality

Something similar to the Flask 'redirect' function - pass it a URL and it redirects the user to a new tab with the specified URL loaded. I feel like I might be able to actually use the Flask method but haven't been able to figure out how (`from flask import redirect` did not work).

***Caveats***
What impact could that feature have on the rest of the product, and should be taken special care of?

Nothing that I can see - maybe a security risk to allow navigation to external domains.

***Other options***
What else could we do (workaround, third-party...)?

NA

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
One easy way is to add the URL as an element of a Navbar component.
It will be opened in a new tab on user click.
`<|navbar|lov={[('/', 'Here'), ('http://www.taipy.io', 'Taipy')]}|>`
We'll look into a possible solution from the python code

**Comment by FredLL-Avaiga** [comment]
Of course, a link can always be added in the standard markdown/html way ...
This requires a user click ...

**Comment by aazimh** [comment]
> Of course, a link can always be added in the standard markdown/html way ...
This requires a user click ...

This is what I was considering, but I couldn't figure out how to get the URL to display as a clickable link, I could only manage a `text` element. This meant the user would have to select the URL, copy, open a new tab and paste, which is too many steps. 

Keep in mind I don't have the URL available on page load - the user has to complete some actions before my code has the URL available - I can save it to a state variable, but not sure what I'd do with it after. That also rules out the navbar approach, as this isn't a link that needs to stick around forever.

**Comment by FredLL-Avaiga** [comment]
OK, I do understand your use-case.
The only solution I can see out of the box is the use of extension to write a custom component for your button/anchor element
https://docs.taipy.io/en/latest/manuals/gui/extension_static_element/#using-properties
Do not hesitate to come back to me.

**Comment by FredLL-Avaiga** [comment]
Here is an example that would work if the URL is known at first render.

```
from taipy.gui import Gui, download
from taipy.gui.extension import ElementLibrary, ElementProperty, Element, PropertyType

class CustomLibrary(ElementLibrary):
    def get_name(self) -> str:
        return "auth"

    def get_elements(self) -> dict:
        def render_auth_link(props):
            url = props.get("url", "")
            return f'<a href="{url}" target="_blank">{props.get("text", "empty")}</a>'
        return ({
          "link":
            Element("text", {
              "text": ElementProperty(PropertyType.string),
              "url": ElementProperty(PropertyType.string),
              },
              render_xhtml=render_auth_link)
          })

url = "http://www.taipy.io"

page = """
## Test Open Url

<|Auth Link|auth.link|url={url}|>
"""

Gui.add_library(CustomLibrary())

Gui(page).run()
```

**Comment by FredLL-Avaiga** [comment]
Coming back to NavBar, you would need to use the lov property which is a dynamic property ie you can add an item with your external link when needed.

**Comment by FlorianJacta** [comment]
Another way would be to use [partials](https://docs.taipy.io/en/latest/manuals/gui/pages/#partials) to create the link you want. A partial is a part of your page that you can update in runtime. With this solution, you don't need to know the link.

```python
from taipy.gui import Gui 

# link to generate
link = ""

# image on which you will be able to click and be redirected
image_link = "https://upload.wikimedia.org/wikipedia/commons/6/6e/Google_Authenticator_for_Android_icon.svg"

md = """
<|Generate link|button|on_action=generate_link|>

<|part|partial={partial}|>
"""

def format_partial(link):
    return f"""
Link: [Taipy]({link})

Here is also a clickable image:

<a href="{link}" rel="Link"><|{image_link}|image|width=32px|width=32px|height=32px|></a>
"""


def generate_link(state):
    state.link = "http://taipy.io/"
    state.partial.update_content(state, format_partial(state.link))


gui = Gui(md)
partial = gui.add_partial("")
gui.run(dark_mode=False)
```

In the beginning, this is what the page looks like with just a button. The partial is empty.

![image](https://user-images.githubusercontent.com/98709993/223726140-19dd71c2-3d09-4732-bb05-a43c2435d7b4.png)

When you click, generate the link. Taipy will update the partial with a 'text' link and an image you can click on to redirect you to your page. Just replace "http://taipy.io/" with the link you are generating.

![image](https://user-images.githubusercontent.com/98709993/223726439-6b5f5241-0b72-4bfd-bc0e-b70c2d117e7f.png)

**Comment by aazimh** [comment]
Thank you both @FredLL-Avaiga and @FlorianJacta for the effort in helping find a solution - I haven't had time to check this out yet but will do so. It seems like yet again partials are the answer for my use case, really need to get around to understanding them :) thank you! Let me know if I should close this or you'd rather keep it open for your reference.

**Comment by FredLL-Avaiga** [comment]
@aazimh You're welcome.
We'll let you close this issue when you're happy with the solution you've chosen.

**Comment by FredLL-Avaiga** [comment]
@aazimh use navigate(state, URL, tab)
