### ISSUE TITLE
Add extension libraries information in extended status

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#627]
**Description**

For debugging purposes, it would be useful to get information on what extension libraries are available when running a Taipy GUI application.

This would use the standard "status" mechanism, with all the possible information (library, elements, modules, component names...).

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
@FabienLelaquais Should it ba available in normal or extended status ?

**Comment by FredLL-Avaiga** [comment]
How do you like: 
```
"libraries": {
  "taipy_extension_example": [
    {
      "js module": "TaipyExtensionExample",
      "elements": [
        {
          "name": "input",
          "js name": "Input"
        },
        {
          "name": "button",
          "js name": "MyButton"
        },
        {
          "name": "list",
          "js name": "MyList"
        },
        {
          "name": "table",
          "js name": "MyTable"
        },
        {
          "name": "title",
          "render xhtml": "render_xhtml"
        },
        {
          "name": "label",
          "js name": "MyLabel"
        }
      ]
    }
  ]
},
```
