### ISSUE TITLE
Add ability to declare different menu icons for dark and light mode

### ISSUE THREAD

**Issue by ghost** [Avaiga/taipy-gui#631]
Could we try to think of a way to let the user define different icons depending of the mode used ? Right now, it's not possible and black icons keep appearing black in dark mode, which makes them almost invisible.

![image](https://user-images.githubusercontent.com/115568883/221543479-be6122ce-1570-474e-a374-9be8ee35e59b.png)
_An icon menu in light mode_

![image](https://user-images.githubusercontent.com/115568883/221543595-ca5c6482-9ea9-4d2e-9af3-e17bab678295.png)
_The same icon menu in dark mode_

For now, the way to work with menu icons in multiple color modes is currently to design colored icons that can display well in both modes, or add a background right to the icon image, which is not ideal and limits styling options.

Another way of allowing icons to adapt would be to render SVG images code in the output DOM to be able to act on the SVG styles with CSS rules, from the component level or from a stylesheet.

**Comment by FredLL-Avaiga** [comment]
@FlorianJacta I suppose you're the right person to ask for these icons ?

**Comment by ghost** [comment]
@FredLL-Avaiga I actually have the whole icon set restyled (from taipy studio) that you can use here. I give them to you right away.

**Comment by ghost** [comment]
@FredLL-Avaiga Here's the whole set in black and white PNG.
[taipycons.zip](https://github.com/Avaiga/taipy-gui/files/10851790/taipycons.zip)

**Comment by FredLL-Avaiga** [comment]
Tx Jauf

**Comment by FredLL-Avaiga** [comment]
@JaufreyTpy 
What do you think of
![image.png](https://images.zenhubusercontent.com/613efb225a9c163a3da6610f/7cfc9316-9b40-47d7-86d8-e5bfd5790b8d)
![image.png](https://images.zenhubusercontent.com/613efb225a9c163a3da6610f/a65131d8-d5c2-4da1-9757-8c41e56abe63)
The taipy icon is embedded as SVG

**Comment by ghost** [comment]
@FredLL-Avaiga Seeing it like this, it seems way better to me. How is the SVG rendered ? In an `<img src="">` or as an inline `<svg>` tag ?

**Comment by FredLL-Avaiga** [comment]
> How is the SVG rendered ? In an `<img src="">` or as an inline `<svg>` tag ?

The content of the svg file is dumped inside the avatar div => svg tag
