### ISSUE TITLE
Use img tag for image control instead of background-image

### ISSUE THREAD

**Issue by ghost** [Avaiga/taipy-gui#632]
On the image control: why not using an <img> tag ? Currently, the image is inserted as a span`s background-image.

Accessibility-wise, content images should not be inserted this way as screen readers can't parse it. And as a pure styling matter, it makes manipulating image dimensions a pain, as we can't just let the image resize homothetically depending on intrinsic size and container limits and flow in the content, as an img would allow it. 

In most case, using an img is the recommanded way to insert images.
And one more thing : the current background image vertical positioning of 40% feels weird. Why not centering the image in its container by default ?

**Comment by FredLL-Avaiga** [comment]
trying to simplify image button with text
![image.png](https://images.zenhubusercontent.com/613efb225a9c163a3da6610f/27b54333-acb3-49f0-bce3-b18cd0a6983b)
@JaufreyTpy How would you go about making the text more visible?
it is in a span that has this style
overflow: "hidden",
    pointerEvents: "none",
    position: "absolute",
    zIndex: 0,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: "inherit",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",

**Comment by ghost** [comment]
Wow... like this, it feels like a very bad idea to me. Whatever the solution we use, if we lay the text over the image there is too much risk for the text to lack readbility. Not mentionning the ugliness...
I would either put the text in a tooltip or center it right under the image, as a caption.

**Comment by FredLL-Avaiga** [comment]
Tooltip then

> I would either put the text in a tooltip or place it under the image.

**Comment by FredLL-Avaiga** [comment]
```
from taipy.gui import Gui

my_image_file = "c:\\users\\...\\fred.png"
my_svg_file = "c:\\users\\...\\LogoTaipy.svg"
my_svg = """
<svg version="1.1"
    viewBox="0 0 300 200"
     xmlns="http://www.w3.org/2000/svg">
  <rect width="100%" height="100%" fill="red" />
  <circle cx="150" cy="100" r="80" fill="green" />
  <text x="150" y="125" font-size="60" text-anchor="middle" fill="white">SVG</text>
</svg>
"""

def on_action(state):
    print("on_action(state)")

page = """
<|toggle|theme|>
<|image|content={my_image_file}|width=unset|>
<|image|content={my_svg_file}|>
<|image|content={my_svg}|>
<|image|content={my_image_file}|label=image label|>
<|image|content={my_svg_file}|label=svg label|>
<|image|content={my_svg}|label=svg label|>
<|image|content={my_image_file}|on_action=on_action|>
<|image|content={my_svg_file}|on_action=on_action|>
<|image|content={my_svg}|on_action=on_action|>
<|image|content={my_image_file}|on_action=on_action|label=image label with action|>
<|image|content={my_svg_file}|on_action=on_action|label=svg label with action|>
<|image|content={my_svg}|on_action=on_action|label=svg label with action|>
"""

Gui(page=page).run()

```
