### ISSUE TITLE
Add CSS components from stylekit as new blocks

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#647]
**Description**
The idea is to create new blocks from the CSS components created for the *Stylekit*. The goals of this improvement would be to :
- simplify the use of new styles,
- being as low-code and user friendly as possible,
- better document the new blocks (these blocks will be documented [here](https://docs.taipy.io/en/latest/manuals/gui/blocks/)). It would be possible to explain in more detailed each block with basic examples, 
- hide the CSS/*class_name* part (unknown for Data Scientists, Python developers)

Examples:

```
<|card|
...
|>
```

```
<|container|
...
|>
```

```
<|sidebar|
...
|>
```

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
We could make classname the default property of part ...

**Comment by FlorianJacta** [comment]
Seems like a great idea! I wonder if we could collect other opinions. Maybe people find it useful to have 'render' as the default property. I have never used it this way for render.

**Comment by FredLL-Avaiga** [comment]
That would make it 
```
<|container|part|
...
|>
```
or
```
<|container|
...
|>

```
