### ISSUE TITLE
Stylekit: Add units to default values in stylekit_variables

### ISSUE THREAD

**Issue by ghost** [Avaiga/taipy-gui#649]
Stylekit `border_radius` and `input_button_height` variables render these CSS custom properties.

```
--border-radius: 8;
--input-button-height: 48;
```

The problem is that CSS does not handle well unitless values.
We should either insert these theme variables values as a string containing an explicit unit (`"8px"` and `"48px"`, respectively, in that case) or give a px unit to the CSS custom property if the value is a number.

**Comment by FredLL-Avaiga** [comment]
default value changed to "<n>px"
