### ISSUE TITLE
Stylekit: Give `borderRadius` and `inputButtonHeight` variables the `string` type in the StyleKitVars interface

### ISSUE THREAD

**Issue by ghost** [Avaiga/taipy-gui#660]
I came across the `gui/src/utils/index.ts` files `StyleKitVars` interface here:

```
interface StyleKitVars {
    // Primary and secondary colors
    colorPrimary: string;
    colorSecondary: string;
    // Contextual color
    colorError: string;
    colorWarning: string;
    colorSuccess: string;
    // Background and elevation color for LIGHT MODE
    colorBackgroundLight: string;
    colorPaperLight: string;
    // Background and elevation color for DARK MODE
    colorBackgroundDark: string;
    colorPaperDark: string;
    // DEFINING FONTS
    // Set main font family
    fontFamily: string;
    // DEFINING SHAPES
    // Base border radius
    borderRadius: number;
    // DEFINING MUI COMPONENTS STYLES
    // Matching input and button height
    inputButtonHeight: number;
}
```

And I wonder if, for the reasons we discussed before, we shouldn't give `borderRadius` and `inputButtonHeight` the `string` type here.

What do you think ?

_Originally posted by @JaufreyTpy in https://github.com/Avaiga/taipy-gui/issues/650#issuecomment-1466369547_

**Comment by FredLL-Avaiga** [comment]
setting theme borderRadius to a string is not supported by Mui
`MUI: The `theme.shape.borderRadius` value (8px) is invalid.`

**Comment by ghost** [comment]
Damned...
Then, if the MUI value has to be a number, we'll have to insert the `px` unit after the value in the CSS custom prop definition, because a unitless number won't work with CSS.
And I'll have to change this statement in the documentation too.

**Comment by FredLL-Avaiga** [comment]
I suppose input_button_height can stay as a string

**Comment by ghost** [comment]
Yes, this one can stay as it is.
