### ISSUE TITLE
Add a way to invoke user function that would return a page

### ISSUE THREAD

**Issue by FredLL-Avaiga** [Avaiga/taipy-gui#669]
**What would that feature address**
Following @dr-irv [proposal](https://github.com/Avaiga/taipy-gui/pull/600), we want to propose a way for a Gui app to allow the rendering of page content from a specific URL. 

***Description of the ideal solution***
1. call a GUI method with a specific path extension and a local function that will be invoked when the URL is requested
  1.1. gui.add_user_content_cb("&lt;extension name>", on_request)
  1.1. in user code def on_request(state: State, path: str): &lt;HTML Content as BytesIO> ...
1. at runtime
  1.1. GUI utility function returns a valid URL from state, extension_name and rest of path. The URL can be used to update web UI
  1.1. when the URL is requested (in the form /taipy-user-content/<extension name>/<rest of path>), on_request is invoked and content is returned
  1.1. as an option, a python utility function can be provided to perform URL request from the UI and show the result in the current tab or a new tab

***Caveats***
The solution should have no impact on the current functionnalities

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
@dr-Irv use on_user_content(state, path, query)

**Comment by Dr-Irv** [comment]
> @Dr-Irv use on_user_content(state, path, query)

I looked at the PR you merged that has `on_user_content()` and `get_user_content_url()`, and it's not clear to me how they interact.  Do you have an example that illustrates how to use them?

**Comment by FredLL-Avaiga** [comment]
Here it is:
```
from taipy.gui import Gui, State, get_user_content_url

curval = 0
uc_url = None

page = """## Test

<|{curval}|slider|>

Current Value: <|{curval}|>

<|Open a new page with user content in iFrame|button|>

<|part|page={uc_url}|>

"""

def on_action(state:State):
    state.uc_url = get_user_content_url(state, f"hello{state.curval}", {"t": "a"})

def on_user_content(state: State, path: str, query: dict):
    return f"""
    <html>
    <body>
    <h1>User rendered with {path} and State.curval={state.curval}</h1>
    <h2>Query: {query}</h2>
    </body>
    </html>
    """

gui = Gui()
gui.add_page("main", page)
gui.run(
    title="User Content Demo",
    debug=True,
    use_reloader=False,
)
```
