### ISSUE TITLE
Enhance organization of complex applications

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#690]
## Faced issue

Building complex applications requires manipulating a lot of Markdown and code surrounding it to create the logic behind it. The goal is to find an efficient way to organize an application between several pages and several sections of your pages. A page with a lot of functionality will be harder to understand and maintain if represented in a single Markdown file and with a long Python code associated with it.

This issue aims to have ways or best practices for creating complex applications in a structured and intuitive manner. This would help further improve the readability, maintainability, and navigation of applications, making the development process even more seamless.

## Desired outcome:

- Clear and intuitive guidance for organizing applications into pages and sections
- Enhanced readability and maintainability of code and markdown
- Improved navigation within the application structure

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by dinhlongviolin1** [comment]
#754, #751 is related
