### ISSUE TITLE
Taipy inside watermark

### ISSUE THREAD

**Issue by orangeluc** [Avaiga/taipy-gui#691]
Is it possible to remove 'Taipy inside' watermark in the dashboard?

**Comment by FredLL-Avaiga** [comment]
Of course, you can set the watermark as an empty string via the Gui config.
`Gui(md).run(watermark="")`

**Comment by FredLL-Avaiga** [comment]
@orangeluc Does this fix your issue ?

**Comment by jrobinAV** [comment]
The ticket has been handled. Closed for lack of an answer.
