### ISSUE TITLE
Add a 'refresh_browser()' function

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#747]
**What would that feature address**

There are situations when the user wants to force the refresh of the client-facing page.
That's typically the case when using the Authentication package where pages dynamically change.

***Description of the ideal solution***

We want a new function: `refresh_browser(state: State)` what would do the thing.

***Other options***

Let the user manutally refresh...

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
I would propose a navigate(state, to, tab, force)
When force == True and it is the current page: refresh (handled on the front end)
