### ISSUE TITLE
Possiblity to have multiline and indent for text visual elements

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#764]
(very) related to Avaiga/taipy#381.

**Description**
The goal is to be able to view as a text, a multiline string with indent.

_**Example of text:**_

```
version: '3.1'
stories:
-   story: loferum ipsi
    steps:
    -   intent: bot_capabilities
        user: What can you do
```

_**What it should look like:**_

![image](https://github.com/Avaiga/taipy-gui/assets/98709993/86102043-5f1d-4113-9230-a3953b36abaf)

In Taipy 2.2.1, no indent or line skip is possible.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by arcanaxion** [comment]
Stumbled upon this issue and thought I'd weigh in. I realise that the `markdown` package outputs:

```html
<p>version: '3.1'\nstories:\n-   story: loferum ipsi\n    steps:\n    -   intent: bot_capabilities\n        user: What can you do</p>
```

which is visually rendered in a single line as:

```
version: '3.1' stories: - story: loferum ipsi steps: - intent: bot_capabilities user: What can you do
```

I'm not familiar with the differences between different Markdown parsers, but some seem to certainly be more forgiving or yield "more expected" results, and I too would like if the example above would result in a multi line output. I find myself putting empty lines between lines very often with taipy.

E.g. GFM renders the example as so:

version: '3.1'
stories:
-   story: loferum ipsi
    steps:
    -   intent: bot_capabilities
        user: What can you do
