### ISSUE TITLE
Styling of component in panes

### ISSUE THREAD

**Issue by ghost** [Avaiga/taipy-gui#766]
**Description**
Hi everyone,
it seems that the styling of element in panes is not fully taken into account.

**How to reproduce**
Simple app :
```
from taipy.gui import Gui, notify
import pandas as pd

#list of kpi (key / value)
tp_kpis = pd.DataFrame(
    {
        "name":["A", "B", "C"],
        "value":["1", "2", "3"]
    }
)

show_kpi = False

def display_kpi(state):
    state.show_kpi = True

main_page = """
<|toggle|theme|>
###Kpis
<|Kpis|button|on_action=display_kpi|>
<|{show_kpi}|pane|anchor=bottom|width=560px|
<|card|
<|{tp_kpis}|table|columns=name; value|show_all=True|width=500px|height=700px|>
|>
|>

<|card|
<|{tp_kpis}|table|columns=name; value|show_all=True|width=500px|height=700px|>
|>
"""
#Run Taipy GUI
gui = Gui(main_page).run(dark_mode=True)
```

**Expected behavior**
Have the proper styling in the pane

**Screenshots**

![image](https://github.com/Avaiga/taipy-gui/assets/102367972/cb1d39bc-2a57-42b1-8878-11972b2593c8)

**Runtime environment**
Please specify relevant indications.
 - OS: Ubuntu 22.04.2 LTS
 - Browser: Chromium

**Comment by FlorianJacta** [comment]
Thank you for your issue! It seems that visual elements or Stylekit components (like tables or card) behaves wrongly in the pane control. We will work on it!

I created a simpler code to reproduce this behavior:

```python
from taipy.gui import Gui

data = {
        "name":["A", "B", "C"],
        "value":["1", "2", "3"]
    }


main_page = """
<|toggle|theme|>

<|{True}|pane|
<|{data}|table|>

<|card|
Here is a **card**{.color-primary}
|>
|>
"""

Gui(main_page).run(dark_mode=False)
```

Screenshot:

![image](https://github.com/Avaiga/taipy-gui/assets/98709993/40964eb6-dae2-410b-b7f0-4562fda07183)
