### ISSUE TITLE
BUG-Scatter Plot doesn't update colors, needs page reload

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-gui#776]
**Description**
Currently when modifying the data in a scatter plot, the position of the points accurately change but the colors don't update. This leads to incorrect coloring of points:

![image](https://github.com/Avaiga/taipy-gui/assets/62465003/f9c61982-22d7-4317-9696-af5039a183e5)

And after a page reload, the points' colors update:

![image](https://github.com/Avaiga/taipy-gui/assets/62465003/0047ece5-5857-48e3-9ff3-551a24db7888)

**How to reproduce**

Create and modify a pandas dataframe with data and color:
```python
state.visual_data = pd.DataFrame(
        {
            "x": state.X[::1000, 0],
            "y": state.X[::1000, 1],
            "color": state.km.labels_[::1000],
        }
    )
```

Add a chart markers visual element
```
<|{visual_data}|chart|mode=markers|x=x|y=y|color=color|>
```

Run the app then modify the data, the points should move but the colors won't update before a page reload.

**Expected behavior**
When the data of a chart visual element is modified, the color data should be re-evaluated to display the correct colors without a page reload.

**Runtime environment**
Please specify relevant indications.
 - OS: Windows
 - Browser: Chrome

**Comment by FredLL-Avaiga** [comment]
Color is part of the chart config
The chart should be updated if the rebuild property is specified
<|{visual_data}|chart|mode=markers|x=x|y=y|color=color|rebuild|>

**Comment by AlexandreSajus** [comment]
Understood thanks, maybe this should be added in the docs in the line chart page

**Comment by FredLL-Avaiga** [comment]
I think there's a paragraph coming on rebuild for table and chart.

**Comment by FabienLelaquais** [comment]
@AlexandreSajus Does [this section](https://docs.taipy.io/en/develop/manuals/gui/viselements/chart/#the-rebuild-property) helps?

**Comment by AlexandreSajus** [comment]
I did not see the section when going through the doc. Ideally, maybe we should add this:
![image](https://github.com/Avaiga/taipy-gui/assets/62465003/4efddf6a-8b02-47b9-a52a-1ac4b8166f50)
Here and in all the other plots' arguments lists:
![image](https://github.com/Avaiga/taipy-gui/assets/62465003/29ba5adc-33e0-4cf8-998a-6fd2c0bbee0b)

Also, why is rebuild not True by default?

You can close this issue if you want

**Comment by FabienLelaquais** [comment]
As for why it's not the default, that's for performance reasons.
'rebuild' requests the entire generation of the component, potentially entirely redefined.
When set to False, it allows for far faster feedback in response to a user action.

**Comment by FabienLelaquais** [comment]
The recommendation is captured in [a dedicated taipy-doc issue](https://github.com/Avaiga/taipy-doc/issues/574).
