### ISSUE TITLE
BUG-Inconsistent behavior for the display of a list of pages with a single page

### ISSUE THREAD

**Issue by vhfgosselin** [Avaiga/taipy-gui#80]
**Description**
If I only need a single page,  then we should use:
gui = Gui(__name__, Markdown(page1))

However, a second option would be:
list_pages = {
    'p1':Markdown(page1)
}
gui = Gui(__name__,pages = list_pages)

however using this code nothing appears on the GUI,  but if I add a second page then it works!
I do not see why having a single page would work using a list of pages.

**Comment by FredLL-Avaiga** [comment]
Can't reproduce the pb ...
If I access https://localhost:5000/ browser is redirected to http://localhost:5000/p1 and shows the page
