### ISSUE TITLE
Ability to style the spinner

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#815]
**What would that feature address**
It would allow the user to style and manipulate the spinner easily.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
taipy-busy css class name added to the spinner
