### ISSUE TITLE
BUG-Multiline Input Visual Element, can't break line

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-gui#824]
**Description**
Using Enter or Shift+Enter while editing text in a multiline input visual element triggers on_action but does not break line

**How to reproduce**
Create a Taipy page with a multiline input visual element

![image](https://github.com/Avaiga/taipy-gui/assets/62465003/70dc0a46-27e8-4899-9d17-cc02606d2f4e)

![image](https://github.com/Avaiga/taipy-gui/assets/62465003/1797ebf9-f1de-47ec-964f-9c8890ba8946)

Press Enter or Shift+Enter while editing the text inside the element

**Expected behavior**
Shift+Enter should break line when editing text in a multiline input element

**Runtime environment**
Please specify relevant indications.
 - OS: Windows 11
 - Browser: Chrome

**Comment by FredLL-Avaiga** [comment]
Does it work if on_action is not defined ?

**Comment by FredLL-Avaiga** [comment]
it would make life easier if you could include a reproduction code example so that one can copy/paste.

**Comment by AlexandreSajus** [comment]
It does work when on_action is not defined. But even if on_action is defined, Shift+Enter should still break line

Sure! Here's a reproduction code:

```python
from taipy.gui import Gui

report = ""


def report_feedback(state):
    return None


page = """
<|{report}|input|on_action=report_feedback|multiline|>
"""

gui = Gui(page)
gui.run(title="Talk To Taipy (alpha)")
```

**Comment by FredLL-Avaiga** [comment]
Does this need to be backported to 2.3.* ?
@FabienLelaquais

**Comment by FredLL-Avaiga** [comment]
backporting to 2.3
