### ISSUE TITLE
New markdown syntax to make nested taipy gui code more readable

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy-gui#827]
**What would that feature address**
Take code like so:

```python
from taipy.gui import Gui

item_list = ["item1", "item2", "item3"]
selected_item = item_list[0]
md = """
<|layout|columns=1 4|

<|{selected_item}|selector|lov={item_list}|label=Item|>

<|part|

<|{selected_item}|>

<|{selected_item}|>

|>
    
|>
"""

Gui(md).run()
```

As I add more layouts and parts (not necessarily further nested), it becomes decreasingly obvious if a line belongs to a "container" (blocks like a part/layout), and if so, which.

***Description of the ideal solution***
Perhaps the code could look like:

```python
md = """
<|layout|columns=1 4|

    <|{selected_item}|selector|lov={item_list}|label=Item|>

    <|part|

        <|{selected_item}|>

        <|{selected_item}|>

    |>
    
|>
"""
```

But then it would get treated as a markdown code block, and won't render as expected.

Some ideas to fix this:

1. Taipy blocks could have a property (e.g. `unnest`) wherein lines within would be `str.lstrip`-ed,
2. Add some prefix to a line to indicate that it shouldn't be treated as a code block (the prefix is also removed when rendered).

Surely there's some better idea though.

***Caveats***
Taipy Studio should be updated to recognize any new syntax.

***Other options***

1. Indenting a line by fewer than 4 spaces prevents it from becoming a code block (best workaround I have),
2. Starting the indented line with a non-breaking space (U+00A0 ` `) works but should be a crime.

Please let me know if there's an existing intended way to make nesting more visually obvious (with or without indents).

Thank you!

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FabienLelaquais** [comment]
Unfortunately, we cannot do that: Taipy GUI needs to respect the Markdown syntax and limitations.
Indentation is a full component of Markdown (starting lists and things like that), so there' s no way we can break this.

However you have two alternatives that might help:
- Using HTML. Although cumbersome for some, indentation can be performed on tags, so you' re good to go.
- Using Taipy GUI's element tag identifiers (see the end of the [section on Markdown syntax for visual elements](https://docs.taipy.io/en/latest/manuals/gui/viselements/#markdown):
    Instead of using '<|'  and '|>', you can use an identifier between '<'  and '|' in the opening tag, and between '|' and '>' in the closing tag. Both must match or you get an error.
     So in you example, you could write:
     ```
     <the_layout|layout|columns=1 4|

     <|{selected_item}|selector|lov={item_list}|label=Item|>

     <the_part|part|

     <|{selected_item}|>

     <|{selected_item}|>

     |the_part>
    
     |the_layout>
     ```

You still don't have identation, but you can spot the opening and closing tags...

Hope this helps.

**Comment by FabienLelaquais** [comment]
Closed for no code change will be made for this one.
