### ISSUE TITLE
Have a default '.css' file to configure a default margin

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#83]
**What would that feature address**
This issue would address the default margin present in the GUI. The default margin is currently 0px. Having no margin is in general not good-looking.

***Description of the ideal solution***
Having a default margin at 20px for example would allow a user to have a more aesthetically pleasing page without creating or changing a '.css' file. So, a default .css file with this code :

```
div#root {
    margin: 20px;
}
```

***Caveats***
It shouldn't have an impact on other elements. However, it would mean that the default margin is for example 20px. Therefore, the user would have to bypass the default parameter by creating his own .css file if he wants to have no margin or a different margin.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
We could define a default left margin of 1em
But that would have an impact on every component ...
ie if you define a chart with 100vw the right side would be out of the margin => scroll bar would appear and vertical layout could then be impacted too

**Comment by FlorianJacta** [comment]
Hmm I see.. it is a problem. It was an idea of Fabien to implement that in order to directly get something that is more great looking. I don't know how to get this better look but keep the other widths consistent... A basic user won't create by itself a css file to change the margin except if we teel him how to do it but he will also find this same problem then.

**Comment by FredLL-Avaiga** [comment]
we could set the left margin as a property to Gui and have a default of None.
This way it would be super easy to change but it would be a user action ;-)
@FabienLelaquais thoughts ?

**Comment by FabienLelaquais** [comment]
I actually would do the opposite.
'margin' would be '1em' by default.
And the user can set it to None if he needs a full working area.
