### ISSUE TITLE
BUG- When a table is filtered, `on_action()` does not pass the correct row number of the original DataFrame

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-gui#835]
**Description**
If a user filters a table, and an `on_action()` callback is set on the table, then the `payload["index"]` contains the row number of the filtered table, but there is no way to know what real row that is in the original `DataFrame`.

We are pretty sure that the same error occurs with `on_edit()` as well.

**How to reproduce**
```python
from typing import Any

import pandas as pd

from taipy.gui import Gui, Markdown, State

table1 = pd.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})

indexval = -1
xval = "-1"
yval = "-1"

page = Markdown(
    """

<|{table1}|table|filter=True|rebuild=True|width=fit-content|on_action=on_action|>

<|Indexval|text|> <|{indexval}|text|>

<|xval|text|> <|{xval}|text|>

<|yval|text|> <|{yval}|text|>

"""
)


def on_action(state: State, var_name: str, action: str, payload: dict[str, Any]):
    indexval = payload["index"]
    xval = state.table1.iloc[indexval]["x"]
    state.xval = str(xval)
    yval = state.table1.iloc[indexval]["y"]
    state.yval = str(yval)
    state.indexval = indexval


if __name__ == "__main__":
    gui = Gui(page=page)
    gui.run(title="Filter Action")

```

Sequence of events:
- Filter the table on "x" "equals" "3"
- That will leave one row.  Choose that row
- The action updates the index values and the corresponding row of the DataFrame, which is not the filtered value

**Expected behavior**
The row number should be of the filtered DataFrame, or there should be some way to know what rows remain after filtering.

**Runtime environment**
Please specify relevant indications.
 - OS:  Windows 10 2H22
 - Browser: Chrome  114.0.5735.134
 - taipy 2.3.1

**Comment by FlorianJacta** [comment]
Good find! Using the index in the payload seems impossible as it corresponds to the filtered data.
