### ISSUE TITLE
Make the creation of the layout columns easier

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#84]
**Description**

This improvement will add to the existing syntax, another way to create columns in the layout parameters. Currently, when we want to create 5 columns in a layout, we write
```
<|layout|columns=1 1 1 1 1
```
The goal would be to change this syntax to make it simpler and easier to read. For example, like this :
```
<|layout|columns=1*5
```
This syntax will create the same layout as before so 5 columns of the same width.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
Do you want to also support 2\*2+3\*1 ?

**Comment by FlorianJacta** [comment]
Well, if it is possible. Why not

**Comment by FredLL-Avaiga** [comment]
Not sure it's clearer that way
The thing is that we support classic css grid column description  
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns
