### ISSUE TITLE
Why is python-dotenv pinned to version 0.19 when version 1.0 was released in February, 2023

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-gui#843]
* Taipy version: 2.3.1
* Python version:  3.10
* Operating System:  Unbuntu Linx

### Description

Why is python-dotenv pinned to version 0.19 when version 1.0 was released in February, 2023 ??

**Comment by deepvoice** [comment]
+1
pandasai requires python-dotenv<2.0.0,>=1.0.0, but you have python-dotenv 0.20.0 which is incompatible.

**Comment by FredLL-Avaiga** [comment]
fixed in 3.0
