### ISSUE TITLE
BUG - File Selector sometimes does not work on Cloud

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-gui#845]
**Description**
Using the file selector visual element on Cloud works on some datasets and not on others

**How to reproduce**
I created a smallest reproducible example for this issue:

Here is the code:
```python
from taipy.gui import Gui
import pandas as pd

data = []
data_path = ""


def data_upload(state):
    state.data = pd.read_csv(state.data_path)


page = """
<|{data_path}|file_selector|on_action=data_upload|>
<|{data}|table|>
"""

Gui(page).run()
```

When running the app locally, I can upload any datasets. But when running it on Cloud, some datasets work and some don't.

I have attached the app (`main.zip`) and two datasets to this issue (`simple_data.csv` and `complex_data.csv`)

[main.zip](https://github.com/Avaiga/taipy-gui/files/12037969/main.zip)
[simple_data.csv](https://github.com/Avaiga/taipy-gui/files/12037972/simple_data.csv)
[complex_data.csv](https://github.com/Avaiga/taipy-gui/files/12037973/complex_data.csv)

The app is currently hosted here: https://bug-file-selector.taipy.cloud/

Loading `simple_data.csv` works both locally and on Cloud.

But loading `complex_data.csv` works only locally, and on Cloud, it errors out with:

```bash
[2023-07-13 09:36:36][Taipy][ERROR] Exception on /taipy-uploads [POST]
Traceback (most recent call last):
  File "/home/alex/apps/bug-file-selector/.venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alex/apps/bug-file-selector/.venv/lib/python3.8/site-packages/flask/app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/alex/apps/bug-file-selector/.venv/lib/python3.8/site-packages/flask/app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "/home/alex/apps/bug-file-selector/.venv/lib/python3.8/site-packages/flask/app.py", line 2138, in make_response
    raise TypeError(
TypeError: The view function for 'taipy_upload.__upload_files' did not return a valid response. The function either returned None or ended without a return statement.
```

**Expected behavior**

The user should be able to upload any files on Cloud using the file selector visual element

**Runtime environment**

 - OS: Windows 11
 - Browser: Chrome

**Comment by FredLL-Avaiga** [comment]
nginx configuration for file > 1.0 MB

**Comment by AlexandreSajus** [comment]
Fixed! But the table does not update without a refresh, even with a rebuild argument

**Comment by AlexandreSajus** [comment]
Fixed!
