### ISSUE TITLE
BUG-Navbar redirection not working correctly

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#863]
**Description**
 If I put a navbar in a page "Data" and I want to navigate to a page called "Test", Taipy tries to navigate to "/Data/Test"

If I put the navbar in the root page, I have "/Test" as expected

**How to reproduce**
A code fragment
```python
from taipy import Gui

pages = {"Data":"<|navbar|> Data", "Test":"<|navbar|> Test"}

Gui(pages=pages).run()
```

Use the navbar to go from one page to the other.

**Expected behavior**
The navbar visual elements should redirect to the appropriate pages/url as a default.

**Screenshots**
![image](https://github.com/Avaiga/taipy-gui/assets/98709993/416a5c47-ae8f-4dcb-87f0-a9ec804daf6c)

**Runtime environment**
Taipy GUI: 2.3.1

**Comment by FredLL-Avaiga** [comment]
https://docs.taipy.io/en/latest/manuals/gui/viselements/navbar/#p-lov says you need to prefix the lov ids with /

**Comment by FredLL-Avaiga** [comment]
What do you think @FlorianJacta ?

**Comment by FlorianJacta** [comment]
Do I must provide a 'lov' now? This was working in previous releases.

**Comment by FredLL-Avaiga** [comment]
oups I thought I saw a lov in the other navbar
