### ISSUE TITLE
Add support for Treemap charts

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#873]
**Description**
Support plotly.js treemap type (needs a new `parents` axis)

See [Treemaps in JavaScript](https://plotly.com/javascript/treemaps/).

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Add relevant demos (doc/examples/charts)

The documentation part is taken care of in [this issue](https://github.com/Avaiga/taipy-doc/issues/514).

**Comment by trantor** [comment]
+1
