### ISSUE TITLE
BUG-Passing a function which returns a dictionary to chart.properties does not always work

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy-gui#897]
**Description**

Per title, I receive this warning: 

```
Warning 1: chart.properties (tp_TpExPr_create_chart_properties_selected_type_TPMDL_1_0) must be a dict.
```

**How to reproduce**

```python
from taipy.gui import Gui, Markdown
import pandas as pd

x_range = range(-10, 11)
df = pd.DataFrame({
    "X": x_range,
    "Y": [x*x for x in x_range],
})

def create_chart_properties(selected_type):
    properties = {
        "x": "X",
        "y": "Y",
        "type": selected_type,
    }
    print(properties)
    return properties

types = ["bar", "line"]
selected_type = types[0]

md = Markdown(
"""
<|{df}|chart|properties={create_chart_properties(selected_type)}|rebuild|>

<|{selected_type}|toggle|lov={types}|>
""")

Gui(md).run()
```

Steps to reproduce:

1. Toggle to "line" -- no immediate changes to the chart
2. Refresh page
  a. Observe that the chart changed to "line"
  b. Also, the warning above is in the terminal
3. Toggle back to "bar" -- no immediate changes to the chart
4. Refresh page
  a. Observe that the chart **did not** change back to "bar"
  b. The warning is printed again

**Expected behavior**
The chart should switch between "bar" and "line" as the toggle control is toggled.

I guess the need to refresh may be related to Avaiga/taipy#466, but I don't know about the warning. Must the `properties` property be a literal dictionary and not a function return value, even when used with `rebuild`?

**Comment by FredLL-Avaiga** [comment]
as for now, properties don't allow chart rebuild.
I can fix the warning (which is a separate issue) but it won't fix this issue.
