### ISSUE TITLE
BUG-slider control: Inline Lov doesn't work in sliders

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#910]
**Description**

If a lov is defined as inlined, it does not seem to be properly initialized.

**How to reproduce**
A code fragment
```
from taipy.gui import Gui

value=["XS","XL"]

def on_change(_, var_name, var_value):
    print(f"New range {var_value}")

page = """
# Slider - Range

<|{value}|slider|lov="XXS";"XS";"S";"M";"L";"XL";"XXL"|>
"""

Gui(page).run()
```

Running this code does not initialize the slider selected values properly.

If instead we use a lov object (`values = ["XXS","XS","S","M","L","XL","XXL"]` and `<|{value}|slider|lov={values}|>`) then this works properly.

**Expected behavior**

Slider values should be properly initializd no matter the code.

**Comment by FredLL-Avaiga** [comment]
it works when we specify the property like so:

> <|{value}|slider|lov=XXS;XS;S;M;L;XL;XXL|>

**Comment by FabienLelaquais** [comment]
You are totally right Fred. Thanks!
