### ISSUE TITLE
Allow the file_download control to trigger a synchronous callback before the download itself.

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#925]
**Description**

The file_download control is designed to download the content of its default property.
The application may need to change that property value depending on different conditions.
The problem we have today is that the setting of that property must be performed as soon as the conditions are met to know what it should be, no matter if the data is downloaded or not, so that unnecessary work may have to be performed.

We want a way for the 'download action' to trigger the setting of the data just before it is really needed.

**Addressing the problem**

A synchronous callback mechanism has to be set up so that user code is executed between the action (the download request) and the download itself (which is the result of triggering an anchor).

**Caveat**

Relying on a roundtrip to the server may have a bad impact on the user experience since the setting of the data can take significant time.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
The discussed solution :
- when content is None, the on_action is triggered on user click (no download)
- the developper can then invoke the `download()` function
- if needed, another callback can be specified to the `download()` function

**Comment by FredLL-Avaiga** [comment]
`<|{None}|file_download|label=do your own download|on_action=download_action|name=a name|>`

```
def download_action(state: State, id: str, action: str, payload: dict):
    # name: payload.get('args')[0] => "a name"
    # url: payload.get('args')[1] => ""
    download(state, "<file path>", "<file name>", "after_download_action")

def after_download action(state: State, id: str, action: str, payload: dict):
    # invoked after download is terminated
    # name: payload.get('args')[0] => "<file name>"
    # url: payload.get('args')[1] => <calculated url>
```
