### ISSUE TITLE
Ensure consistency of the `on_action` callback signature

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#963]
**Description**

Taipy 3.0 has changed the `on_action` callback for some controls to make it consistent across the board.
However this signature is used also in other callbacks. Namely:
- table:  `on_add`, `on_delete` and `on_edit`
- chart: `on_range_change`
- pane: `on_close`

We need to make sure all these are aligned just like the generic `on_action`.

**Outcome**
- All those 'on_action'-like callbacks have a similar signature: state, id, payload.
- This is properly documented in the viselements.json files.

**Comment by FredLL-Avaiga** [comment]
all those cb are called from the front end via the createSendActionNameAction function: ie they're all treated by the Gui.__on_action() method.
We need to update the viselements.json though
