### ISSUE TITLE
Add plotly.express-like syntax for specifying color and pattern_shape

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy-gui#980]
**Description**
Plotly Express allows a handy `px.scatter(df, x="sepal_length", y="sepal_width", color="species")` syntax which creates `df.species.unique().size` traces, each with a different color, and traces are toggleable on the legend. I could not find a simple way to replicate this with taipy.

![plotly_iris](https://github.com/Avaiga/taipy-gui/assets/48582724/8f77ce0c-8e8d-4038-af5f-77bb3df18b63)

## Existing: Color column

With #270 allowing to specify a column name with color values, I can do the following:

```python
import pandas as pd
from taipy.gui import Gui, Markdown
import plotly.express as px

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")
species_to_color = {species: px.colors.qualitative.Plotly[i] for i, species in enumerate(df["species"].unique())}
df["color"] = df.species.map(species_to_color)
#      sepal_length  sepal_width  petal_length  petal_width    species    color
# 0             5.1          3.5           1.4          0.2     setosa  #636EFA
# 1             4.9          3.0           1.4          0.2     setosa  #636EFA
# 2             4.7          3.2           1.3          0.2     setosa  #636EFA
# 3             4.6          3.1           1.5          0.2     setosa  #636EFA
# 4             5.0          3.6           1.4          0.2     setosa  #636EFA

md = Markdown(
"""
# Color

<|{df}|chart|mode=markers|x=sepal_length|y=sepal_width|color=color|text=species|layout={dict(showlegend=True)}|>
""")

gui = Gui(md)
gui.run(dark_mode=False)
```

Which gives me:
![taipy_color](https://github.com/Avaiga/taipy-gui/assets/48582724/da341675-bbb5-40d3-ab87-e2d141a74e18)

**Limitation:** I am missing out on the legend where I can toggle on/off traces for specific flower species.

## Existing: Indexed y

Another existing implementation is to index the y property like so:

```python
df_pivot = df.pivot_table(columns="species", index="sepal_length", values="sepal_width").rename_axis(None, axis="columns").reset_index()
#     sepal_length    setosa  versicolor  virginica
# 0            4.3  3.000000         NaN        NaN
# 1            4.4  3.033333         NaN        NaN
# 2            4.5  2.300000         NaN        NaN
# 3            4.6  3.325000         NaN        NaN
# 4            4.7  3.200000         NaN        NaN
# 5            4.8  3.180000         NaN        NaN

md = "<|{df_pivot}|chart|mode=markers|x=sepal_length|y[1]=setosa|y[2]=versicolor|y[3]=virginica|>"
```
![taipy_pivot](https://github.com/Avaiga/taipy-gui/assets/48582724/8fce39b3-901f-4188-9a8a-d4b558da853d)

**Limitation:** I don't want to hard code the 3 flower species names because I may eventually have more flower species, or I may filter the df and have some species be absent. Unless I know exactly what species are present in the df ahead of time, I would have to dynamically generate the y properties, which is tedious.

## Specifying pattern shape

Also, plotly express allows the `pattern_shape` parameter which I can combine with `color` to create the following:

```python
test_df.sample(5)
#           date     flower letter  value
# 5   2022-01-03       Rose      D    4.0
# 25  2022-01-04  Sunflower      D  218.0
# 102 2022-01-09  Sunflower      E  301.0
# 28  2022-01-04  Sunflower      F  229.0
# 75  2022-01-08       Lily      D   35.0

fig = px.bar(
    test_df, x="date", y="value", color="letter", 
    pattern_shape="flower", pattern_shape_map={"ROSE": ".", "LILY": "+", "SUNFLOWER": "x"}
)
fig.update_traces(marker_line_color='black', marker_line_width=1)
```

![image](https://github.com/Avaiga/taipy-gui/assets/48582724/0708552f-1bcb-4005-ba1d-a64d4b85e4ea)

The `color` (and `pattern_shape`) parameters of plotly express are great for visualising additional dimensions in data, and work with "naturally" structured data. It would be great if taipy offers a similar simple way for doing this.

Thank you!

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by vhfgosselin** [comment]
We can provide additional dimensions:
## using the symbol (marker) dimension:
![image](https://github.com/Avaiga/taipy-gui/assets/20767690/6d42bab7-f718-418d-a89d-4b7743f58db8)

## now using a combination of dimensions using color and size with a scatter chart
![image](https://github.com/Avaiga/taipy-gui/assets/20767690/05c1adf3-a26d-49f1-8005-ae454dda860f)

**Comment by FredLL-Avaiga** [comment]
Now, you can put your figure in the content property of the part block control

**Comment by arcanaxion** [comment]
> Now, you can put your figure in the content property of the part block control

Works like a charm!

**Comment by FlorianJacta** [comment]
@arcanaxion do you think this issue is correctly covered by Taipy?

**Comment by arcanaxion** [comment]
> @arcanaxion do you think this issue is correctly covered by Taipy?

Not entirely, but I don't have any good suggestions on what to do about it.

Say I want to plot `n` (not known ahead of time) traces in taipy. I can think of these 2 existing options:

## 1. content property

Literally use plotly.express with the content property. Code looks clean and easy to understand.

```python
from taipy.gui import Gui, Markdown
import plotly.express as px

df = px.data.stocks()

def create_fig(selected_tickers):
    chart_df = df.melt(id_vars="date", var_name="Ticker", value_name="Closing")
    chart_df = chart_df[chart_df.Ticker.isin(selected_tickers)]
    return px.line(chart_df, x="date", y="Closing", color="Ticker")

ticker_list = df.columns.to_list()[1:]
selected_tickers = ticker_list[:3]

md = Markdown(
"""
<|{selected_tickers}|selector|lov={ticker_list}|multiple|dropdown|>

<|part|content={create_fig(selected_tickers)}|height=70vh|>
"""
)

Gui(page=md).run(run_browser=False)
```

## 2. taipy partials

Result looks much better than the content iframe method. But I feel like the code is still too complicated for a simple chart that new users might be deterred.

```python
from taipy.gui import Gui, Markdown
import plotly.express as px

df = px.data.stocks()

def create_chart_partial(selected_tickers):
    y_params = "|".join([f"y[{i+1}]={ticker}" for i, ticker in enumerate(selected_tickers)])
    return f"<|{{df}}|chart|x=date|{y_params}|>"

ticker_list = df.columns.to_list()[1:]
selected_tickers = ticker_list[:3]

md = Markdown(
"""
<|{selected_tickers}|selector|lov={ticker_list}|multiple|dropdown|on_change={lambda s: s.partial.update_content(s, create_chart_partial(s.selected_tickers))}|>

<|part|partial={partial}|>
"""
)

gui = Gui(page=md)
partial = gui.add_partial(create_chart_partial(selected_tickers))
gui.run(run_browser=False)
```

## Possible proposal

I think it'd be nice if something like this could yield the chart like in Option 2. Note the `express` property.

```python
from taipy.gui import Gui, Markdown
import plotly.express as px

df = px.data.stocks()
chart_df = df.melt(id_vars="date", var_name="Ticker", value_name="Closing")

ticker_list = df.columns.to_list()[1:]
selected_tickers = ticker_list[:3]

md = Markdown(
"""
<|{selected_tickers}|selector|lov={ticker_list}|multiple|dropdown|>

<|{chart_df[chart_df.Ticker.isin(selected_tickers)]}|chart|x=date|y=Closing|color=Ticker|express|>
"""
)

Gui(page=md).run(run_browser=False)
```

It's not a big issue anymore because we now have the content property, but I think the chart control itself could still be enhanced further (such as with this proposed px-like syntax).

**Comment by FlorianJacta** [comment]
What do you think about reopening this issue but going from a high priority to medium?

**Comment by FredLL-Avaiga** [comment]
I think it would be best to create a new improvement issue
