### ISSUE TITLE
BUG-Scenario config with id "default" does not appear in scenario_selector configurations

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy-gui#995]
**Description**
Scenario config with id `"default"` does not appear in scenario_selector configurations.

**How to reproduce**

```python
import taipy as tp
from taipy import Config

x_cfg = Config.configure_pickle_data_node(id="x", default_data=5)
y_cfg = Config.configure_data_node(id="y")

def square(x): 
    return x**2
task1_cfg = Config.configure_task(id="task1", function=square, input=x_cfg, output=y_cfg)

scenario_cfg = Config.configure_scenario(id="default", task_configs=[task1_cfg])

selected_scenario = None
md = """<|{selected_scenario}|scenario_selector|>"""

if __name__ == "__main__":
    tp.Core().run()
    tp.Gui(md).run()
```

**Expected behavior**
The scenario should show up in the scenario_selector configuration list -- or `Config.configure_scenario` should raise an error if the id is reserved.

**Screenshots**

![image](https://github.com/Avaiga/taipy-gui/assets/48582724/d5b73417-3790-439c-bafd-b891f12607c8)

**Runtime environment**
Please specify relevant indications.
 - OS: [e.g. Linux, Windows] and version
 - Browser: [e.g. Chrome, Edge, Safari] and version
and any other relevant information.

**Comment by jrobinAV** [comment]
Hello, 

Indeed 'default' is a restricted `config_id`. Taipy core should prevent you from building such a scenario config. Here is a `taipy-core` ticket to improve user experience on that.
https://github.com/Avaiga/taipy/issues/411
Please feel free to add comments on it.

I am closing the ticket for duplication.
